const Map<String, Map<String, String>> kTranslationOverrides = {
  'en': {
    'save_failed': 'Save failed',
    'theme_sync_error': 'Theme sync error',
    'settings_legal': 'Settings & legal',
    'system_preferences': 'System preferences',
    'focus_protocols': 'Focus protocols',
    'notification_channels': 'Notification channels',
    'prepare_home_screen_blackout': 'Prepare home screen for Blackout',
    'focus_session_duration': 'Session duration',
    'focus_short_break': 'Short break',
    'focus_auto_start_breaks': '自动开始休息',
    'onboarding_step_of': 'Step {step} of {total}',
    'onboarding_log_in': 'Log in',
    'onboarding_enter_wakeapp': 'Enter WakeApp',
    'onboarding_adjust_later_settings':
        'You can adjust this later in Settings',
    'onboarding_continue': 'Continue',
    'onboarding_next': 'Next',
    'onboarding_slide_operate_title': 'Operate like a CEO',
    'onboarding_slide_operate_subtitle':
        'Tasks, habits, calendar, and focus in one execution system.',
    'onboarding_slide_habits_title': 'Build compounding habits',
    'onboarding_slide_habits_subtitle':
        'Track consistency daily and recover quickly when you miss.',
    'onboarding_slide_focus_title': 'Protect deep work',
    'onboarding_slide_focus_subtitle':
        'Use focus sessions and blocking to reduce context switching. On iPhone, blocking uses Apple Screen Time / Family Controls APIs and requires permission on that device.',
    'onboarding_questionnaire_title': 'Initialize your system',
    'onboarding_questionnaire_subtitle':
        'Define how you operate before entering the system',
    'onboarding_primary_orientation': 'Primary orientation',
    'onboarding_current_level': 'Current level',
    'onboarding_main_constraint': 'Main constraint',
    'onboarding_system_theme': 'System theme',
    'onboarding_system_theme_subtitle':
        '定义你系统的视觉环境',
    'onboarding_system_profile': 'System profile',
    'onboarding_orientation': 'Orientation',
    'onboarding_level': 'Level',
    'onboarding_constraint': 'Constraint',
    'onboarding_theme': 'Theme',
    'onboarding_goal_execution': 'Execution',
    'onboarding_goal_consistency': 'Consistency',
    'onboarding_goal_focus': 'Focus',
    'onboarding_goal_planning': 'Planning',
    'onboarding_level_beginner': 'Beginner',
    'onboarding_level_intermediate': 'Intermediate',
    'onboarding_level_advanced': 'Advanced',
    'onboarding_constraint_distractions': 'Distractions',
    'onboarding_constraint_overload': 'Overload',
    'onboarding_constraint_inconsistency': 'Inconsistency',
    'onboarding_theme_premium_badge': 'Premium',
    'setup_back_in_wakeapp': 'Back in WakeApp',
    'setup_syncing_permission': 'Syncing your permission…',
    'setup_preparing': 'Preparing setup…',
    'setup_step_of': 'Step {step} of {total}',
    'setup_steps_label': '{total} steps',
    'setup_welcome_title': 'Screen Time setup',
    'setup_welcome_subtitle':
        'A quick, calm setup so protection feels effortless.',
    'setup_what_unlocks': 'What this unlocks',
    'setup_unlock_instant_blocking': 'Instant blocking when an app opens.',
    'setup_unlock_usage_limits': 'Accurate usage limits in the background.',
    'setup_unlock_focus_blackout': 'Focus and blackout sessions that hold.',
    'setup_takes_45s':
        'Takes about 45 seconds. You can redo this any time in Screen Time settings.',
    'setup_return_auto':
        "We'll return you to WakeApp automatically after each permission.",
    'setup_start': 'Start setup',
    'setup_accessibility_title': 'Unlock instant protection',
    'setup_accessibility_subtitle':
        'WakeApp only detects the active app so it can react instantly.',
    'setup_accessibility_reassurance':
        'No messages, content, or screens are read. Everything stays on-device.',
    'setup_usage_title': 'Keep limits accurate',
    'setup_usage_subtitle':
        'Usage access keeps limits and sessions reliable in the background.',
    'setup_overlay_title': 'Show a gentle block screen',
    'setup_overlay_subtitle':
        'This lets WakeApp place a clean block screen when needed.',
    'setup_step_tap_open_settings': 'Tap "Open settings".',
    'setup_step_enable_service':
        'Enable Screen Time under Installed services.',
    'setup_step_allow_service': 'Allow Screen Time in the list.',
    'setup_step_allow_overlay': 'Allow "Display over other apps".',
    'setup_step_return_auto': "We'll bring you back automatically.",
    'setup_if_switch_disabled':
        'If the switch is disabled, open App info → Allow restricted settings.',
    'setup_if_missing_service':
        'If Screen Time is missing, scroll to Downloaded services.',
    'setup_if_missing_open_app':
        'If Screen Time is missing, open Settings → Apps → Screen Time.',
    'setup_then_open_usage_access': 'Then open Usage access and allow it.',
    'setup_if_cant_toggle_overlay':
        "If you can't toggle it, open Special app access → Display over other apps.",
    'setup_enable_wakeapp_and_return': 'Then enable WakeApp and return.',
    'setup_enabled': 'Enabled',
    'setup_not_enabled': 'Not enabled',
    'setup_quick_steps': 'Quick steps',
    'setup_switch_locked': 'If the switch is locked',
    'setup_permission_granted': 'Permission granted',
    'setup_continue': 'Continue',
    'setup_open_settings': 'Open settings',
    'setup_success_title': 'All set',
    'setup_success_subtitle':
        'Screen Time is configured and ready to protect your focus.',
    'setup_success_instant_blocking': 'Instant blocking on protected apps.',
    'setup_success_usage_limits': 'Usage limits enforced on-device.',
    'setup_success_focus_blackout': 'Focus and blackout sessions ready.',
    'setup_open_screen_time': 'Open Screen Time',
    'ios_setup_preparing': 'Preparing Screen Time…',
    'ios_setup_progress_label': 'Screen Time',
    'ios_setup_step_1_of_2': 'Step 1 of 2',
    'ios_setup_step_2_of_2': 'Step 2 of 2',
    'ios_setup_intro_title': 'Set up Screen Time',
    'ios_setup_intro_subtitle':
        "This takes less than a minute. We'll request one Apple permission so Screen Time can enforce focus rules on this iPhone.",
    'ios_setup_what_get': "What you'll get",
    'ios_setup_benefit_instant_blocking_title': 'Instant blocking',
    'ios_setup_benefit_instant_blocking_subtitle':
        'Blocked apps close immediately during sessions.',
    'ios_setup_benefit_private_title': 'Private by design',
    'ios_setup_benefit_private_subtitle':
        "Screen Time data stays on-device and isn't shared.",
    'ios_setup_benefit_reliable_title': 'Reliable focus sessions',
    'ios_setup_benefit_reliable_subtitle':
        'Blackout and focus rules stay active in real time.',
    'ios_setup_start': 'Start setup',
    'ios_setup_permission_allow_title': 'Allow Screen Time access',
    'ios_setup_permission_unavailable_title': 'Screen Time unavailable',
    'ios_setup_permission_unavailable_subtitle':
        'This device cannot grant Apple Screen Time access.',
    'ios_setup_permission_allow_subtitle':
        "Screen Time access lets WakeApp enforce blocks and focus rules using Apple's on-device APIs.",
    'ios_setup_steps_title': 'Steps',
    'ios_setup_instruction_1': 'Tap "Open Settings".',
    'ios_setup_instruction_2': 'Choose WakeApp in the list.',
    'ios_setup_instruction_3': 'Enable Screen Time access.',
    'ios_setup_instruction_4': 'Return to WakeApp.',
    'ios_setup_unsupported_build':
        'Screen Time access is only available on supported iPhone builds.',
    'ios_setup_permission_granted': 'Permission granted',
    'ios_setup_access_turned_off': 'Access turned off',
    'ios_setup_waiting_approval': 'Waiting for approval',
    'ios_setup_completed': 'Completed',
    'ios_setup_ready_title': 'Screen Time is ready',
    'ios_setup_ready_subtitle':
        'You can now block apps and websites instantly during Focus or Blackout sessions.',
    'ios_setup_next': 'Next',
    'ios_setup_next_subtitle':
        'Pick the apps or sites you want to protect.',
    'ios_setup_open_screen_time': 'Open Screen Time',
    'ios_setup_continue': 'Continue',
    'auth_signin_error_title': 'Sign-in error',
    'auth_invalid_email_title': 'Invalid email',
    'auth_invalid_email_message': 'Please enter a valid email address.',
    'auth_password_required_title': 'Password required',
    'auth_password_required_message':
        'Please enter your password to continue.',
    'auth_reset_password_title': 'Reset password',
    'auth_reset_password_enter_email_first':
        'Enter your account email first, then try again.',
    'auth_check_email_title': 'Check your email',
    'auth_check_email_reset_message':
        'If an account exists for {email}, a password reset email has been sent.',
    'auth_login_subtitle':
        'Sign in to restore your system, sync your data, and continue where you left off.',
    'auth_secure_sync': 'Secure cloud sync across your devices.',
    'auth_sign_in': 'Sign in',
    'auth_use_same_credentials':
        'Use the same email and password you created for WakeApp.',
    'auth_email': 'Email',
    'auth_email_placeholder': 'name@example.com',
    'auth_password': 'Password',
    'auth_forgot_password': 'Forgot password?',
    'auth_new_to_wakeapp': 'New to WakeApp?',
    'auth_create_account': 'Create account',
    'auth_account_setup_error_title': 'Account setup error',
    'auth_name_required_title': 'Name required',
    'auth_name_required_message':
        'Please enter your name to create the account.',
    'auth_weak_password_title': 'Weak password',
    'auth_weak_password_message':
        'Use at least 8 characters for your password.',
    'auth_password_mismatch_title': 'Password mismatch',
    'auth_password_mismatch_message':
        'The password confirmation does not match.',
    'auth_check_email_signup_message':
        'Your account was created. Please confirm your email address before signing in.',
    'auth_create_account_title': 'Create your account',
    'auth_create_account_subtitle':
        'Set up your WakeApp login once, then use it across your devices.',
    'auth_account_details': 'Account details',
    'auth_account_details_subtitle':
        'Choose the details you will use to sign in later.',
    'auth_full_name': 'Full name',
    'auth_your_name': 'Your name',
    'auth_confirm_password_label': 'Confirm password',
    'auth_confirm_password_placeholder': 'Confirm password',
    'auth_already_registered': 'Already registered?',
    'blackout_prep_intro_title': 'Prepare your screen for Blackout',
    'blackout_prep_intro_body':
        'Some system apps stay visible on iPhone. Group them in one folder for a cleaner Blackout.',
    'blackout_prep_intro_goal':
        'Goal: create a calmer Home Screen in under 20 seconds.',
    'blackout_prep_demo_title': 'Group secondary apps during focus',
    'blackout_prep_demo_body':
        'FaceTime, Maps, Files, Home, Find My… Group them to reduce visual noise.',
    'blackout_prep_demo_primary': 'Optimize my screen',
    'blackout_prep_checklist_title': 'Do it in 20 seconds',
    'blackout_prep_checklist_body': 'When you are done, come back here.',
    'blackout_prep_step_hold_app': 'Long-press an app icon',
    'blackout_prep_step_drag_on_other': 'Drag it over another app',
    'blackout_prep_step_create_folder':
        'Create a folder named "Out of Focus"',
    'blackout_prep_step_add_system_apps':
        'Add visible system apps into that folder',
    'blackout_prep_done': 'Done',
    'blackout_prep_animation_calm_screen': 'Calmer screen',
    'blackout_prep_animation_folder_name': 'Out of Focus',
    'create': 'Create',
    'done': 'Done',
    'theme_carbon_system': 'Carbon System',
    'theme_ember_protocol': 'Ember Protocol',
    'theme_royal_violet': 'Royal Violet',
    'theme_modern_desert': 'Modern Desert',
    'theme_cloud_studio': 'Cloud Studio',
    'focus_starter_enter_focus': 'Enter Focus',
    'focus_starter_configure_session': 'Configure Session',
    'focus_starter_session_title': 'Session Title',
    'focus_starter_session_placeholder': 'Deep work session...',
    'focus_starter_link_task': 'Link Task',
    'focus_starter_no_tasks': 'No tasks available',
    'focus_starter_session_length': 'Session Length',
    'focus_starter_start_focus': 'Start Focus',
    'leaderboard_title': 'Friends & Leaderboard',
    'leaderboard_friends_tab': 'Friends',
    'leaderboard_global_tab': 'Global',
    'leaderboard_top_performers': 'Top Performers',
    'leaderboard_empty': 'No leaderboard data yet',
    'leaderboard_you': 'You',
    'leaderboard_friend': 'Friend',
    'leaderboard_your_position': 'Your Position',
    'leaderboard_no_friends': 'No friends added yet',
    'leaderboard_add_friends_hint': 'Add friends to compare progress!',
    'leaderboard_invite_friends': 'Invite Friends',
    'leaderboard_invite_message':
        'Join me on WakeApp to compare progress and win streaks: ',
    'leaderboard_invite_ready': 'Invite ready',
    'leaderboard_invite_copied': 'Invite link copied to clipboard.',
    'leaderboard_rank_streak': '{rank} • {streak} day streak',
    'leaderboard_your_friends_count': 'Your Friends ({count})',
    'rank_awakened': 'Awakened',
    'rank_immortal': 'Immortal',
    'rank_diamond': 'Diamond',
    'rank_platinum': 'Platinum',
    'rank_gold': 'Gold',
    'rank_silver': 'Silver',
    'rank_bronze': 'Bronze',
    'rank_asleep': 'Asleep',
    'rank_ladder': 'Rank Ladder',
    'rank_unlocked_today': 'Unlocked today',
    'rank_unlocked_local_pending_sync': 'Unlocked locally — sync pending',
    'rank_top_reached': 'Top rank reached',
    'rank_path_to': 'Path to {rank}',
    'rank_progress': 'Progress',
    'rank_highest_tier': 'You are currently at the highest tier.',
    'rank_requirements_completed_sync_pending':
        'Your next rank requirements are completed. The server rank is still catching up.',
    'rank_your_stats': 'Your Stats',
    'rank_days_in_app': 'Days in app',
    'rank_streak': 'Streak',
    'rank_days_value': '{count} days',
    'rank_unlocked': 'Unlocked',
    'rank_locked': 'Locked',
    'rank_req_500_day_streak': '500 day streak',
    'rank_req_250h_focus': '250h Focus',
    'rank_req_250h_ceo': '250h CEO',
    'rank_req_365_day_streak': '365 day streak',
    'rank_req_200h_focus': '200h Focus',
    'rank_req_100h_ceo': '100h CEO',
    'rank_req_180_day_streak': '180 day streak',
    'rank_req_90_day_streak': '90 day streak',
    'rank_req_60h_focus': '60h Focus',
    'rank_req_50_day_streak': '50 day streak',
    'rank_req_15_days_in_app': '15 days in app',
    'rank_req_10_day_streak': '10 day streak',
    'rank_req_7_days_in_app': '7 days in app',
    'rank_req_1_focus_session': '1 Focus session',
    'rank_req_starting_rank': 'Starting rank',
    'calendar_schedule_title': 'Schedule',
    'calendar_swipe_stats_hint': 'Swipe right for stats & insights →',
    'calendar_swipe_calendar_hint': '← Swipe left for calendar view',
    'calendar_types_loading': 'Types…',
    'calendar_types_button': 'Types',
    'calendar_weekday_mon': 'MON',
    'calendar_weekday_tue': 'TUE',
    'calendar_weekday_wed': 'WED',
    'calendar_weekday_thu': 'THU',
    'calendar_weekday_fri': 'FRI',
    'calendar_weekday_sat': 'SAT',
    'calendar_weekday_sun': 'SUN',
    'calendar_event_all_day': 'All day',
    'calendar_event_birthday_repeats_yearly': 'Birthday • repeats yearly',
    'calendar_event_minutes_short': 'min',
    'calendar_event_weekly_short': 'weekly',
    'calendar_stats_overloaded_day': 'Overloaded Day',
    'calendar_stats_overload_too_many_hours':
        '{hours}h scheduled - reduce load.',
    'calendar_stats_overload_no_breaks':
        'Back-to-back events without a clear break.',
    'calendar_stats_overload_too_many_events':
        '{count} events planned - high intensity.',
    'calendar_stats_habit_conflict': 'Habit Conflict',
    'calendar_stats_habit_conflict_message': '{habits} habit(s) + {hours}h events.',
    'calendar_focus_opportunity': 'Focus Opportunity',
    'calendar_focus_reason_no_events': 'Day is free - perfect for deep work',
    'calendar_focus_reason_light_schedule':
        'Light schedule - ideal for a focus block',
    'calendar_focus_reason_busy_schedule':
        'Dense day - keep one short focus sprint',
    'calendar_start_focus': 'Start Focus',
    'calendar_real_free_time': 'Real Free Time',
    'calendar_real_free_time_subtitle': 'After events & sleep',
    'calendar_week_overview': 'Week Overview',
    'calendar_week_scheduled': 'Scheduled',
    'calendar_week_important': 'Important',
    'calendar_week_free_time': 'Free Time',
    'calendar_week_priority': 'Priority',
    'calendar_week_free_hours': '{percent}% of waking hours remain free',
    'calendar_add_event_title': 'Create New Event',
    'calendar_add_event_error_title': 'Cannot create event',
    'calendar_add_event_focus_requires_start_time':
        'Focus session requires a start time.',
    'calendar_add_event_section_type': 'EVENT TYPE',
    'calendar_add_event_type_standard': 'Standard',
    'calendar_add_event_type_birthday': 'Birthday',
    'calendar_add_event_type_focus_session': 'Focus Session',
    'calendar_add_event_loading_types': 'Loading types…',
    'calendar_add_event_type': 'Type',
    'calendar_add_event_create_types': 'Create event types',
    'calendar_add_event_manage_types': 'Manage types',
    'calendar_add_event_section_title': 'TITLE',
    'calendar_add_event_title_placeholder_birthday':
        'Birthday title (e.g. Marie)',
    'calendar_add_event_title_placeholder_focus': 'Focus title',
    'calendar_add_event_title_placeholder_default': 'Title',
    'calendar_add_event_section_description': 'DESCRIPTION',
    'calendar_add_event_description_placeholder_birthday': 'Notes (optional)',
    'calendar_add_event_description_placeholder_focus': 'Context (optional)',
    'calendar_add_event_description_placeholder_default':
        'Description (optional)',
    'calendar_add_event_section_date': 'DATE',
    'calendar_add_event_section_duration': 'DURATION',
    'calendar_add_event_minutes': 'minutes',
    'calendar_add_event_repeat_weekly': 'Repeat weekly',
    'calendar_add_event_section_actions': 'ACTION BUTTONS',
    'calendar_add_event_create_birthday': 'Create Birthday',
    'calendar_add_event_plan_session': 'Plan Session',
    'tasks_new_task': 'New Task',
    'tasks_add_task': 'Add Task',
    'tasks_task_title_placeholder': 'Task title',
    'tasks_no_description': 'No description',
    'tasks_set_deadline': 'Set deadline',
    'tasks_est_duration': 'Estimated duration',
    'tasks_duration_unplanned': 'Unplanned',
    'tasks_duration_under_30min': 'Under 30 min',
    'tasks_duration_1_hour': '1 hour',
    'tasks_duration_2_hours': '2 hours',
    'tasks_duration_half_day': 'Half day',
    'tasks_duration_1_day': '1 day',
    'tasks_duration_several_days': 'Several days',
    'tasks_priority': 'Priority',
    'tasks_importance_low': 'Low',
    'tasks_importance_average': 'Average',
    'tasks_importance_essential': 'Essential',
    'tasks_importance_crucial': 'Crucial',
    'tasks_sync_deadline_to_calendar': 'Sync deadline to calendar',
    'tasks_picker_clear': 'Clear',
    'tasks_picker_done': 'Done',
    'tasks_your_priorities': 'Your Priorities',
    'tasks_no_priorities': 'No priorities yet',
    'tasks_no_priorities_subtitle':
        '添加你的第一个优先任务，开始执行。',
    'tasks_other_tasks': 'Other Tasks',
    'tasks_swipe_hint_list': 'Swipe to complete or reopen',
    'tasks_tab_title_todo': 'To-Do',
    'tasks_tab_subtitle_todo': 'Execution list',
    'tasks_tab_title_matrix': 'Matrix',
    'tasks_tab_subtitle_matrix': 'Priority map',
    'tasks_tab_title_history': 'History',
    'tasks_tab_subtitle_history': 'Completed tasks',
    'tasks_matrix_impact_axis': 'Impact',
    'tasks_matrix_time_axis': 'Effort',
    'tasks_matrix_do_now': 'Do now',
    'tasks_matrix_do_now_subtitle': 'High impact, low effort',
    'tasks_matrix_plan': 'Plan',
    'tasks_matrix_plan_subtitle': 'High impact, high effort',
    'tasks_matrix_if_time': 'If time',
    'tasks_matrix_if_time_subtitle': 'Low impact, low effort',
    'tasks_matrix_eliminate': 'Eliminate',
    'tasks_matrix_eliminate_subtitle': 'Low impact, high effort',
    'tasks_history_empty': 'No completed tasks yet',
    'tasks_swipe_hint_history': 'Swipe to reopen',
    'tasks_swipe_hint_matrix': 'Tap to view details',
    'tasks_empty': 'No tasks',
    'tasks_initialize_task': 'Initialize your first task',
    'tasks_due': 'Due',
    'tasks_created': 'Created',
    'tasks_description': 'Description',
    'tasks_mark_done': 'Mark done',
    'tasks_reopen_task': 'Reopen task',
  },
  'fr': {
    'save_failed': "Échec de l'enregistrement",
    'theme_sync_error': 'Erreur de synchronisation du thème',
    'settings_legal': 'Paramètres et légal',
    'system_preferences': 'Préférences système',
    'focus_protocols': 'Protocoles Focus',
    'notification_channels': 'Canaux de notification',
    'prepare_home_screen_blackout': 'Préparer l'écran pour Blackout',
    'focus_session_duration': 'Durée de session',
    'focus_short_break': 'Pause courte',
    'focus_auto_start_breaks': 'Démarrage auto des pauses',
    'onboarding_step_of': 'Étape {step} sur {total}',
    'onboarding_log_in': 'Connexion',
    'onboarding_enter_wakeapp': 'Entrer dans WakeApp',
    'onboarding_adjust_later_settings':
        'Tu pourras ajuster cela plus tard dans les paramètres',
    'onboarding_continue': 'Continuer',
    'onboarding_next': 'Suivant',
    'onboarding_slide_operate_title': 'Pilote comme un CEO',
    'onboarding_slide_operate_subtitle':
        "Tâches, habitudes, calendrier et focus dans un seul système d'exécution.",
    'onboarding_slide_habits_title': 'Crée des habitudes cumulatives',
    'onboarding_slide_habits_subtitle':
        'Suis ta régularité chaque jour et rebondis vite après un écart.',
    'onboarding_slide_focus_title': 'Protège le travail profond',
    'onboarding_slide_focus_subtitle':
        "Utilise des sessions Focus et le blocage pour réduire les changements de contexte. Sur iPhone, le blocage utilise les API Apple Screen Time / Family Controls et nécessite l'autorisation sur cet appareil.",
    'onboarding_questionnaire_title': 'Initialise ton système',
    'onboarding_questionnaire_subtitle':
        "Définis ton mode de fonctionnement avant d'entrer dans le système",
    'onboarding_primary_orientation': 'Orientation principale',
    'onboarding_current_level': 'Niveau actuel',
    'onboarding_main_constraint': 'Contrainte principale',
    'onboarding_system_theme': 'Thème du système',
    'onboarding_system_theme_subtitle':
        "Définit l'environnement visuel de ton système",
    'onboarding_system_profile': 'Profil système',
    'onboarding_orientation': 'Orientation',
    'onboarding_level': 'Niveau',
    'onboarding_constraint': 'Contrainte',
    'onboarding_theme': 'Thème',
    'onboarding_goal_execution': 'Exécution',
    'onboarding_goal_consistency': 'Régularité',
    'onboarding_goal_focus': 'Focus',
    'onboarding_goal_planning': 'Planification',
    'onboarding_level_beginner': 'Débutant',
    'onboarding_level_intermediate': 'Intermédiaire',
    'onboarding_level_advanced': 'Avancé',
    'onboarding_constraint_distractions': 'Distractions',
    'onboarding_constraint_overload': 'Surcharge',
    'onboarding_constraint_inconsistency': 'Inconstance',
    'onboarding_theme_premium_badge': 'Premium',
    'setup_back_in_wakeapp': 'Retour dans WakeApp',
    'setup_syncing_permission': "Synchronisation de l'autorisation…",
    'setup_preparing': 'Préparation de la configuration…',
    'setup_step_of': 'Étape {step} sur {total}',
    'setup_steps_label': '{total} étapes',
    'setup_welcome_title': 'Configuration Screen Time',
    'setup_welcome_subtitle':
        'Une configuration rapide et calme pour une protection fluide.',
    'setup_what_unlocks': 'Ce que cela active',
    'setup_unlock_instant_blocking':
        "Blocage instantané dès l'ouverture d'une app.",
    'setup_unlock_usage_limits':
        "Limites d'usage fiables en arrière-plan.",
    'setup_unlock_focus_blackout': 'Sessions Focus et Blackout robustes.',
    'setup_takes_45s':
        'Environ 45 secondes. Tu peux refaire cela à tout moment dans les réglages Screen Time.',
    'setup_return_auto':
        'Nous te ramenons automatiquement dans WakeApp après chaque permission.',
    'setup_start': 'Commencer',
    'setup_accessibility_title': 'Déverrouille la protection instantanée',
    'setup_accessibility_subtitle':
        "WakeApp détecte uniquement l'app active pour réagir immédiatement.",
    'setup_accessibility_reassurance':
        "Aucun message, contenu ou écran n'est lu. Tout reste sur l'appareil.",
    'setup_usage_title': 'Assure des limites exactes',
    'setup_usage_subtitle':
        "L'accès usage garantit des limites et sessions fiables en arrière-plan.",
    'setup_overlay_title': 'Affiche un écran de blocage propre',
    'setup_overlay_subtitle':
        "Cela permet à WakeApp d'afficher un écran de blocage net si nécessaire.",
    'setup_step_tap_open_settings': 'Appuie sur « Ouvrir les réglages ».',
    'setup_step_enable_service':
        'Active Screen Time dans les services installés.',
    'setup_step_allow_service': 'Autorise Screen Time dans la liste.',
    'setup_step_allow_overlay': 'Autorise « Afficher par-dessus les apps ».',
    'setup_step_return_auto': 'Nous te ramenons automatiquement.',
    'setup_if_switch_disabled':
        'Si le bouton est grisé, ouvre Infos app → Autoriser réglages restreints.',
    'setup_if_missing_service':
        'Si Screen Time est absent, fais défiler vers Services téléchargés.',
    'setup_if_missing_open_app':
        'Si Screen Time est absent, ouvre Réglages → Apps → Screen Time.',
    'setup_then_open_usage_access':
        "Ensuite ouvre Accès à l'usage et autorise-le.",
    'setup_if_cant_toggle_overlay':
        'Si le bouton ne change pas, ouvre Accès spécial → Afficher par-dessus.',
    'setup_enable_wakeapp_and_return': 'Active WakeApp puis reviens.',
    'setup_enabled': 'Activé',
    'setup_not_enabled': 'Non activé',
    'setup_quick_steps': 'Étapes rapides',
    'setup_switch_locked': 'Si le bouton est bloqué',
    'setup_permission_granted': 'Autorisation accordée',
    'setup_continue': 'Continuer',
    'setup_open_settings': 'Ouvrir les réglages',
    'setup_success_title': 'Tout est prêt',
    'setup_success_subtitle':
        'Screen Time est configuré et prêt à protéger ton focus.',
    'setup_success_instant_blocking': 'Blocage instantané sur apps protégées.',
    'setup_success_usage_limits': "Limites d'usage appliquées sur l'appareil.",
    'setup_success_focus_blackout':
        'Sessions Focus et Blackout prêtes.',
    'setup_open_screen_time': 'Ouvrir Screen Time',
    'ios_setup_preparing': 'Préparation de Screen Time…',
    'ios_setup_progress_label': 'Screen Time',
    'ios_setup_step_1_of_2': 'Étape 1 sur 2',
    'ios_setup_step_2_of_2': 'Étape 2 sur 2',
    'ios_setup_intro_title': 'Configurer Screen Time',
    'ios_setup_intro_subtitle':
        "Cela prend moins d'une minute. Nous demanderons une autorisation Apple pour appliquer les règles Focus sur cet iPhone.",
    'ios_setup_what_get': 'Ce que tu obtiens',
    'ios_setup_benefit_instant_blocking_title': 'Blocage instantané',
    'ios_setup_benefit_instant_blocking_subtitle':
        'Les apps bloquées se ferment immédiatement pendant les sessions.',
    'ios_setup_benefit_private_title': 'Confidentialité intégrée',
    'ios_setup_benefit_private_subtitle':
        "Les données Screen Time restent sur l'appareil et ne sont pas partagées.",
    'ios_setup_benefit_reliable_title': 'Sessions Focus fiables',
    'ios_setup_benefit_reliable_subtitle':
        'Les règles Blackout et Focus restent actives en temps réel.',
    'ios_setup_start': 'Commencer',
    'ios_setup_permission_allow_title': "Autoriser l'accès Screen Time",
    'ios_setup_permission_unavailable_title': 'Screen Time indisponible',
    'ios_setup_permission_unavailable_subtitle':
        "Cet appareil ne peut pas accorder l'accès Apple Screen Time.",
    'ios_setup_permission_allow_subtitle':
        "L'accès Screen Time permet à WakeApp d'appliquer le blocage et les règles Focus via les API Apple locales.",
    'ios_setup_steps_title': 'Étapes',
    'ios_setup_instruction_1': 'Appuie sur « Ouvrir les réglages ».',
    'ios_setup_instruction_2': 'Choisis WakeApp dans la liste.',
    'ios_setup_instruction_3': "Active l'accès Screen Time.",
    'ios_setup_instruction_4': 'Reviens dans WakeApp.',
    'ios_setup_unsupported_build':
        "L'accès Screen Time est disponible uniquement sur les builds iPhone compatibles.",
    'ios_setup_permission_granted': 'Autorisation accordée',
    'ios_setup_access_turned_off': 'Accès désactivé',
    'ios_setup_waiting_approval': 'En attente de validation',
    'ios_setup_completed': 'Terminé',
    'ios_setup_ready_title': 'Screen Time est prêt',
    'ios_setup_ready_subtitle':
        'Tu peux maintenant bloquer instantanément apps et sites pendant Focus ou Blackout.',
    'ios_setup_next': 'Prochaine étape',
    'ios_setup_next_subtitle':
        'Choisis les apps ou sites que tu veux protéger.',
    'ios_setup_open_screen_time': 'Ouvrir Screen Time',
    'ios_setup_continue': 'Continuer',
    'auth_signin_error_title': 'Erreur de connexion',
    'auth_invalid_email_title': 'Email invalide',
    'auth_invalid_email_message': 'Veuillez saisir une adresse email valide.',
    'auth_password_required_title': 'Mot de passe requis',
    'auth_password_required_message':
        'Veuillez saisir votre mot de passe pour continuer.',
    'auth_reset_password_title': 'Réinitialiser le mot de passe',
    'auth_reset_password_enter_email_first':
        "Saisis d'abord ton email de compte, puis réessaie.",
    'auth_check_email_title': 'Vérifie ta boîte mail',
    'auth_check_email_reset_message':
        'Si un compte existe pour {email}, un email de réinitialisation a été envoyé.',
    'auth_login_subtitle':
        "Connecte-toi pour restaurer ton système, synchroniser tes données et reprendre là où tu t'es arrêté.",
    'auth_secure_sync': 'Synchronisation cloud sécurisée entre tes appareils.',
    'auth_sign_in': 'Connexion',
    'auth_use_same_credentials':
        'Utilise le même email et mot de passe que pour ton compte WakeApp.',
    'auth_email': 'Email',
    'auth_email_placeholder': 'nom@exemple.com',
    'auth_password': 'Mot de passe',
    'auth_forgot_password': 'Mot de passe oublié ?',
    'auth_new_to_wakeapp': 'Nouveau sur WakeApp ?',
    'auth_create_account': 'Créer un compte',
    'auth_account_setup_error_title': 'Erreur de création du compte',
    'auth_name_required_title': 'Nom requis',
    'auth_name_required_message':
        'Veuillez saisir votre nom pour créer le compte.',
    'auth_weak_password_title': 'Mot de passe faible',
    'auth_weak_password_message':
        'Utilise au moins 8 caractères pour ton mot de passe.',
    'auth_password_mismatch_title': 'Mots de passe différents',
    'auth_password_mismatch_message':
        'La confirmation du mot de passe ne correspond pas.',
    'auth_check_email_signup_message':
        'Ton compte a été créé. Merci de confirmer ton adresse email avant de te connecter.',
    'auth_create_account_title': 'Crée ton compte',
    'auth_create_account_subtitle':
        'Configure ton accès WakeApp une seule fois, puis utilise-le sur tous tes appareils.',
    'auth_account_details': 'Informations du compte',
    'auth_account_details_subtitle':
        'Choisis les informations que tu utiliseras pour te connecter ensuite.',
    'auth_full_name': 'Nom complet',
    'auth_your_name': 'Ton nom',
    'auth_confirm_password_label': 'Confirmer le mot de passe',
    'auth_confirm_password_placeholder': 'Confirmer le mot de passe',
    'auth_already_registered': 'Déjà inscrit ?',
    'blackout_prep_intro_title': 'Prépare ton écran pour Blackout',
    'blackout_prep_intro_body':
        'Certaines apps système restent visibles sur iPhone. Regroupe-les dans un dossier pour un Blackout plus propre.',
    'blackout_prep_intro_goal':
        "Objectif : créer un écran d'accueil plus calme en moins de 20 secondes.",
    'blackout_prep_demo_title': 'Range les apps secondaires pendant ton focus',
    'blackout_prep_demo_body':
        'FaceTime, Plans, Fichiers, Maison, Localiser… Regroupe-les pour un écran plus calme.',
    'blackout_prep_demo_primary': "J'optimise mon écran",
    'blackout_prep_checklist_title': 'Fais-le en 20 secondes',
    'blackout_prep_checklist_body': "Quand c'est terminé, reviens ici.",
    'blackout_prep_step_hold_app': 'Maintiens une app',
    'blackout_prep_step_drag_on_other': 'Fais-la glisser sur une autre',
    'blackout_prep_step_create_folder': 'Crée un dossier "Hors Focus"',
    'blackout_prep_step_add_system_apps': 'Ajoute les apps système visibles',
    'blackout_prep_done': "C'est fait",
    'blackout_prep_animation_calm_screen': 'Écran plus calme',
    'blackout_prep_animation_folder_name': 'Hors Focus',
    'create': 'Créer',
    'done': 'Terminé',
    'theme_carbon_system': 'Système Carbone',
    'theme_ember_protocol': 'Protocole Ember',
    'theme_royal_violet': 'Violet Royal',
    'theme_modern_desert': 'Désert Moderne',
    'theme_cloud_studio': 'Studio Nuage',
    'focus_starter_enter_focus': 'Entrer en Focus',
    'focus_starter_configure_session': 'Configurer la session',
    'focus_starter_session_title': 'Titre de session',
    'focus_starter_session_placeholder': 'Session de deep work...',
    'focus_starter_link_task': 'Lier une tâche',
    'focus_starter_no_tasks': 'Aucune tâche disponible',
    'focus_starter_session_length': 'Durée de session',
    'focus_starter_start_focus': 'Démarrer Focus',
    'leaderboard_title': 'Amis & Classement',
    'leaderboard_friends_tab': 'Amis',
    'leaderboard_global_tab': 'Global',
    'leaderboard_top_performers': 'Top Performers',
    'leaderboard_empty': 'Aucune donnée de classement pour le moment',
    'leaderboard_you': 'Toi',
    'leaderboard_friend': 'Ami',
    'leaderboard_your_position': 'Ta position',
    'leaderboard_no_friends': 'Aucun ami ajouté',
    'leaderboard_add_friends_hint': 'Ajoute des amis pour comparer ta progression !',
    'leaderboard_invite_friends': 'Inviter des amis',
    'leaderboard_invite_message':
        'Rejoins-moi sur WakeApp pour comparer progression et win streak : ',
    'leaderboard_invite_ready': 'Invitation prête',
    'leaderboard_invite_copied': "Lien d'invitation copié.",
    'leaderboard_rank_streak': '{rank} • streak {streak} jours',
    'leaderboard_your_friends_count': 'Tes amis ({count})',
    'rank_awakened': 'Éveillé',
    'rank_immortal': 'Immortel',
    'rank_diamond': 'Diamant',
    'rank_platinum': 'Platine',
    'rank_gold': 'Or',
    'rank_silver': 'Argent',
    'rank_bronze': 'Bronze',
    'rank_asleep': 'Endormi',
    'rank_ladder': 'Échelle des rangs',
    'rank_unlocked_today': "Débloqué aujourd'hui",
    'rank_unlocked_local_pending_sync': 'Débloqué localement — sync en attente',
    'rank_top_reached': 'Rang maximal atteint',
    'rank_path_to': 'Chemin vers {rank}',
    'rank_progress': 'Progression',
    'rank_highest_tier': 'Tu es actuellement au rang le plus élevé.',
    'rank_requirements_completed_sync_pending':
        'Les exigences du prochain rang sont remplies. Le rang serveur est encore en rattrapage.',
    'rank_your_stats': 'Tes stats',
    'rank_days_in_app': "Jours dans l'app",
    'rank_streak': 'Streak',
    'rank_days_value': '{count} jours',
    'rank_unlocked': 'Débloqué',
    'rank_locked': 'Verrouillé',
    'rank_req_500_day_streak': 'Streak 500 jours',
    'rank_req_250h_focus': '250h Focus',
    'rank_req_250h_ceo': '250h CEO',
    'rank_req_365_day_streak': 'Streak 365 jours',
    'rank_req_200h_focus': '200h Focus',
    'rank_req_100h_ceo': '100h CEO',
    'rank_req_180_day_streak': 'Streak 180 jours',
    'rank_req_90_day_streak': 'Streak 90 jours',
    'rank_req_60h_focus': '60h Focus',
    'rank_req_50_day_streak': 'Streak 50 jours',
    'rank_req_15_days_in_app': "15 jours dans l'app",
    'rank_req_10_day_streak': 'Streak 10 jours',
    'rank_req_7_days_in_app': "7 jours dans l'app",
    'rank_req_1_focus_session': '1 session Focus',
    'rank_req_starting_rank': 'Rang de départ',
    'calendar_schedule_title': 'Planning',
    'calendar_swipe_stats_hint': 'Balaye à droite pour stats & insights →',
    'calendar_swipe_calendar_hint': '← Balaye à gauche pour la vue calendrier',
    'calendar_types_loading': 'Types…',
    'calendar_types_button': 'Types',
    'calendar_weekday_mon': 'LUN',
    'calendar_weekday_tue': 'MAR',
    'calendar_weekday_wed': 'MER',
    'calendar_weekday_thu': 'JEU',
    'calendar_weekday_fri': 'VEN',
    'calendar_weekday_sat': 'SAM',
    'calendar_weekday_sun': 'DIM',
    'calendar_event_all_day': 'Toute la journée',
    'calendar_event_birthday_repeats_yearly': 'Anniversaire • se répète chaque année',
    'calendar_event_minutes_short': 'min',
    'calendar_event_weekly_short': 'hebdo',
    'calendar_stats_overloaded_day': 'Journée surchargée',
    'calendar_stats_overload_too_many_hours':
        '{hours}h planifiées - réduis la charge.',
    'calendar_stats_overload_no_breaks':
        'Événements enchaînés sans vraie pause.',
    'calendar_stats_overload_too_many_events':
        '{count} événements planifiés - intensité élevée.',
    'calendar_stats_habit_conflict': "Conflit d'habitudes",
    'calendar_stats_habit_conflict_message': "{habits} habitude(s) + {hours}h d'événements.",
    'calendar_focus_opportunity': 'Opportunité Focus',
    'calendar_focus_reason_no_events':
        'Journée libre - parfaite pour du deep work',
    'calendar_focus_reason_light_schedule':
        'Planning léger - idéal pour un bloc Focus',
    'calendar_focus_reason_busy_schedule':
        'Journée dense - garde un sprint Focus court',
    'calendar_start_focus': 'Démarrer Focus',
    'calendar_real_free_time': 'Vrai temps libre',
    'calendar_real_free_time_subtitle': 'Après événements & sommeil',
    'calendar_week_overview': 'Vue semaine',
    'calendar_week_scheduled': 'Planifié',
    'calendar_week_important': 'Important',
    'calendar_week_free_time': 'Temps libre',
    'calendar_week_priority': 'Priorité',
    'calendar_week_free_hours':
        '{percent}% des heures éveillées restent libres',
    'calendar_add_event_title': 'Créer un nouvel événement',
    'calendar_add_event_error_title': "Impossible de créer l'événement",
    'calendar_add_event_focus_requires_start_time':
        'Une session Focus nécessite une heure de début.',
    'calendar_add_event_section_type': "TYPE D'ÉVÉNEMENT",
    'calendar_add_event_type_standard': 'Standard',
    'calendar_add_event_type_birthday': 'Anniversaire',
    'calendar_add_event_type_focus_session': 'Session Focus',
    'calendar_add_event_loading_types': 'Chargement des types…',
    'calendar_add_event_type': 'Type',
    'calendar_add_event_create_types': "Créer des types d'événement",
    'calendar_add_event_manage_types': 'Gérer les types',
    'calendar_add_event_section_title': 'TITRE',
    'calendar_add_event_title_placeholder_birthday':
        'Titre anniversaire (ex. Marie)',
    'calendar_add_event_title_placeholder_focus': 'Titre Focus',
    'calendar_add_event_title_placeholder_default': 'Titre',
    'calendar_add_event_section_description': 'DESCRIPTION',
    'calendar_add_event_description_placeholder_birthday': 'Notes (optionnel)',
    'calendar_add_event_description_placeholder_focus':
        'Contexte (optionnel)',
    'calendar_add_event_description_placeholder_default':
        'Description (optionnel)',
    'calendar_add_event_section_date': 'DATE',
    'calendar_add_event_section_duration': 'DURÉE',
    'calendar_add_event_minutes': 'minutes',
    'calendar_add_event_repeat_weekly': 'Répéter chaque semaine',
    'calendar_add_event_section_actions': "BOUTONS D'ACTION",
    'calendar_add_event_create_birthday': 'Créer anniversaire',
    'calendar_add_event_plan_session': 'Planifier session',
    'tasks_new_task': 'Nouvelle tâche',
    'tasks_add_task': 'Ajouter une tâche',
    'tasks_task_title_placeholder': 'Titre de la tâche',
    'tasks_no_description': 'Aucune description',
    'tasks_set_deadline': 'Définir une échéance',
    'tasks_est_duration': 'Durée estimée',
    'tasks_duration_unplanned': 'Non planifiée',
    'tasks_duration_under_30min': 'Moins de 30 min',
    'tasks_duration_1_hour': '1 heure',
    'tasks_duration_2_hours': '2 heures',
    'tasks_duration_half_day': 'Demi-journée',
    'tasks_duration_1_day': '1 jour',
    'tasks_duration_several_days': 'Plusieurs jours',
    'tasks_priority': 'Priorité',
    'tasks_importance_low': 'Faible',
    'tasks_importance_average': 'Moyenne',
    'tasks_importance_essential': 'Essentielle',
    'tasks_importance_crucial': 'Cruciale',
    'tasks_sync_deadline_to_calendar': "Synchroniser l'échéance au calendrier",
    'tasks_picker_clear': 'Effacer',
    'tasks_picker_done': 'Terminé',
    'tasks_your_priorities': 'Tes priorités',
    'tasks_no_priorities': 'Aucune priorité pour le moment',
    'tasks_no_priorities_subtitle':
        "Ajoute ta première priorité pour lancer l'exécution.",
    'tasks_other_tasks': 'Autres tâches',
    'tasks_swipe_hint_list': 'Balaye pour terminer ou rouvrir',
    'tasks_tab_title_todo': 'To-Do',
    'tasks_tab_subtitle_todo': "Liste d'exécution",
    'tasks_tab_title_matrix': 'Matrice',
    'tasks_tab_subtitle_matrix': 'Carte des priorités',
    'tasks_tab_title_history': 'Historique',
    'tasks_tab_subtitle_history': 'Tâches terminées',
    'tasks_matrix_impact_axis': 'Impact',
    'tasks_matrix_time_axis': 'Effort',
    'tasks_matrix_do_now': 'Faire maintenant',
    'tasks_matrix_do_now_subtitle': 'Impact élevé, effort faible',
    'tasks_matrix_plan': 'Planifier',
    'tasks_matrix_plan_subtitle': 'Impact élevé, effort élevé',
    'tasks_matrix_if_time': 'Si temps',
    'tasks_matrix_if_time_subtitle': 'Impact faible, effort faible',
    'tasks_matrix_eliminate': 'Éliminer',
    'tasks_matrix_eliminate_subtitle': 'Impact faible, effort élevé',
    'tasks_history_empty': 'Aucune tâche terminée',
    'tasks_swipe_hint_history': 'Balaye pour rouvrir',
    'tasks_swipe_hint_matrix': 'Appuie pour voir le détail',
    'tasks_empty': 'Aucune tâche',
    'tasks_initialize_task': 'Initialise ta première tâche',
    'tasks_due': 'Échéance',
    'tasks_created': 'Créée',
    'tasks_description': 'Description',
    'tasks_mark_done': 'Marquer comme terminée',
    'tasks_reopen_task': 'Rouvrir la tâche',
  },
  'es': {
    'app_name': 'WakeApp',
    'today': 'Hoy',
    'avg_7d': 'PROM. 7D',
    'settings': 'Ajustes',
    'retry': 'Reintentar',
    'please_try_again': 'Vuelve a intentarlo en un momento.',
    'permission_required': 'Permiso requerido',
    'language_not_available': 'No disponible',
    'create': 'Crear',
    'creating': 'Creando…',
    'done': 'Listo',
    'duration': 'Duración',
    'untitled': 'Sin título',

    'onboarding_step_of': 'Paso {step} de {total}',
    'onboarding_log_in': 'Iniciar sesión',
    'onboarding_enter_wakeapp': 'Entrar en WakeApp',
    'onboarding_adjust_later_settings':
        'Puedes ajustarlo más tarde en Configuración',
    'onboarding_continue': 'Continuar',
    'onboarding_next': 'Siguiente',
    'onboarding_slide_operate_title': 'Opera como un CEO',
    'onboarding_slide_operate_subtitle':
        'Tareas, hábitos, calendario y focus en un solo sistema de ejecución.',
    'onboarding_slide_habits_title': 'Construye hábitos compuestos',
    'onboarding_slide_habits_subtitle':
        'Sigue la constancia diaria y recupérate rápido cuando falles.',
    'onboarding_slide_focus_title': 'Protege el trabajo profundo',
    'onboarding_slide_focus_subtitle':
        'Usa sesiones Focus y bloqueo para reducir cambios de contexto. En iPhone, el bloqueo usa APIs de Apple Screen Time / Family Controls y requiere permiso en este dispositivo.',
    'onboarding_questionnaire_title': 'Inicializa tu sistema',
    'onboarding_questionnaire_subtitle':
        'Define cómo operas antes de entrar en el sistema',
    'onboarding_primary_orientation': 'Orientación principal',
    'onboarding_current_level': 'Nivel actual',
    'onboarding_main_constraint': 'Restricción principal',
    'onboarding_system_theme': 'Tema del sistema',
    'onboarding_system_theme_subtitle':
        'Define el entorno visual de tu sistema',
    'onboarding_system_profile': 'Perfil del sistema',
    'onboarding_orientation': 'Orientación',
    'onboarding_level': 'Nivel',
    'onboarding_constraint': 'Restricción',
    'onboarding_theme': 'Tema',
    'onboarding_goal_execution': 'Ejecución',
    'onboarding_goal_consistency': 'Constancia',
    'onboarding_goal_focus': 'Focus',
    'onboarding_goal_planning': 'Planificación',
    'onboarding_level_beginner': 'Principiante',
    'onboarding_level_intermediate': 'Intermedio',
    'onboarding_level_advanced': 'Avanzado',
    'onboarding_constraint_distractions': 'Distracciones',
    'onboarding_constraint_overload': 'Sobrecarga',
    'onboarding_constraint_inconsistency': 'Inconstancia',
    'onboarding_theme_premium_badge': 'Premium',
    'setup_back_in_wakeapp': 'De vuelta en WakeApp',
    'setup_syncing_permission': 'Sincronizando tus permisos…',
    'setup_welcome_title': 'Configuración de Tiempo en pantalla',
    'setup_welcome_subtitle':
        'Una configuración rápida y tranquila para que la protección sea sin esfuerzo.',
    'setup_what_unlocks': 'Qué desbloquea esto',
    'setup_unlock_instant_blocking':
        'Bloqueo instantáneo cuando se abre una app.',
    'setup_unlock_usage_limits': 'Límites de uso fiables en segundo plano.',
    'setup_unlock_focus_blackout': 'Sesiones de Focus y Blackout que se mantienen.',
    'setup_takes_45s':
        'Tarda unos 45 segundos. Puedes repetirlo en cualquier momento desde los ajustes de Tiempo en pantalla.',
    'setup_return_auto':
        'Volveremos a WakeApp automáticamente tras cada permiso.',
    'setup_accessibility_title': 'Desbloquea protección instantánea',
    'setup_accessibility_subtitle':
        'WakeApp solo detecta la app activa para poder reaccionar al instante.',
    'setup_accessibility_reassurance':
        'No se leen mensajes, contenido ni pantallas. Todo se queda en el dispositivo.',
    'setup_usage_title': 'Mantén los límites exactos',
    'setup_usage_subtitle':
        'El acceso de uso mantiene fiables los límites y las sesiones en segundo plano.',
    'setup_overlay_title': 'Muestra una pantalla de bloqueo suave',
    'setup_overlay_subtitle':
        'Esto permite a WakeApp mostrar una pantalla de bloqueo limpia cuando sea necesario.',
    'setup_step_tap_open_settings': 'Toca "Abrir ajustes".',
    'setup_step_enable_service':
        'Activa Screen Time en Servicios instalados.',
    'setup_step_allow_service': 'Permite Screen Time en la lista.',
    'setup_step_allow_overlay': 'Permite "Mostrar sobre otras apps".',
    'setup_step_return_auto': 'Te traeremos de vuelta automáticamente.',
    'setup_if_switch_disabled':
        'Si el interruptor está desactivado, abre Info de la app → Permitir ajustes restringidos.',
    'setup_if_missing_service':
        'Si Screen Time no aparece, desplázate hasta Servicios descargados.',
    'setup_if_missing_open_app':
        'Si Screen Time no aparece, abre Ajustes → Apps → Screen Time.',
    'setup_then_open_usage_access':
        'Luego abre Acceso de uso y concédelo.',
    'setup_if_cant_toggle_overlay':
        'Si no puedes activarlo, abre Acceso especial a apps → Mostrar sobre otras apps.',
    'setup_enable_wakeapp_and_return': 'Luego activa WakeApp y vuelve.',
    'setup_enabled': 'Activado',
    'setup_not_enabled': 'No activado',
    'setup_quick_steps': 'Pasos rápidos',
    'setup_switch_locked': 'Si el interruptor está bloqueado',
    'setup_permission_granted': 'Permiso concedido',
    'setup_success_subtitle':
        'Tiempo en pantalla está configurado y listo para proteger tu Focus.',
    'setup_success_instant_blocking':
        'Bloqueo instantáneo en apps protegidas.',
    'setup_success_usage_limits': 'Límites de uso aplicados en el dispositivo.',
    'setup_success_focus_blackout': 'Sesiones de Focus y Blackout listas.',
    'setup_preparing': 'Preparando configuración…',
    'setup_step_of': 'Paso {step} de {total}',
    'setup_steps_label': '{total} pasos',
    'setup_start': 'Iniciar configuración',
    'setup_continue': 'Continuar',
    'setup_open_settings': 'Abrir ajustes',
    'setup_success_title': 'Todo listo',
    'setup_open_screen_time': 'Abrir Screen Time',
    'ios_setup_preparing': 'Preparando Screen Time…',
    'ios_setup_step_1_of_2': 'Paso 1 de 2',
    'ios_setup_step_2_of_2': 'Paso 2 de 2',
    'ios_setup_intro_title': 'Configurar Screen Time',
    'ios_setup_start': 'Iniciar configuración',
    'ios_setup_permission_allow_title': 'Permitir acceso a Screen Time',
    'ios_setup_permission_unavailable_title': 'Screen Time no disponible',
    'ios_setup_steps_title': 'Pasos',
    'ios_setup_instruction_1': 'Toca "Abrir ajustes".',
    'ios_setup_instruction_2': 'Elige WakeApp en la lista.',
    'ios_setup_instruction_3': 'Activa el acceso de Screen Time.',
    'ios_setup_instruction_4': 'Vuelve a WakeApp.',
    'ios_setup_permission_granted': 'Permiso concedido',
    'ios_setup_access_turned_off': 'Acceso desactivado',
    'ios_setup_waiting_approval': 'Esperando aprobación',
    'ios_setup_completed': 'Completado',
    'ios_setup_ready_title': 'Screen Time está listo',
    'ios_setup_next': 'Siguiente',
    'ios_setup_open_screen_time': 'Abrir Screen Time',
    'ios_setup_continue': 'Continuar',
    'auth_signin_error_title': 'Error de inicio de sesión',
    'auth_invalid_email_title': 'Correo inválido',
    'auth_invalid_email_message':
        'Introduce una dirección de correo válida.',
    'auth_password_required_title': 'Contraseña obligatoria',
    'auth_password_required_message':
        'Introduce tu contraseña para continuar.',
    'auth_reset_password_title': 'Restablecer contraseña',
    'auth_reset_password_enter_email_first':
        'Primero escribe tu correo de cuenta y vuelve a intentarlo.',
    'auth_check_email_title': 'Revisa tu correo',
    'auth_check_email_reset_message':
        'Si existe una cuenta para {email}, se ha enviado un correo para restablecer la contraseña.',
    'auth_login_subtitle':
        'Inicia sesión para restaurar tu sistema, sincronizar tus datos y continuar donde lo dejaste.',
    'auth_secure_sync': 'Sincronización segura en la nube entre dispositivos.',
    'auth_sign_in': 'Iniciar sesión',
    'auth_use_same_credentials':
        'Usa el mismo correo y contraseña que creaste para WakeApp.',
    'auth_email': 'Correo',
    'auth_email_placeholder': 'nombre@ejemplo.com',
    'auth_password': 'Contraseña',
    'auth_forgot_password': '¿Olvidaste tu contraseña?',
    'auth_new_to_wakeapp': '¿Nuevo en WakeApp?',
    'auth_create_account': 'Crear cuenta',
    'auth_account_setup_error_title': 'Error al crear la cuenta',
    'auth_name_required_title': 'Nombre obligatorio',
    'auth_name_required_message':
        'Introduce tu nombre para crear la cuenta.',
    'auth_weak_password_title': 'Contraseña débil',
    'auth_weak_password_message':
        'Usa al menos 8 caracteres en tu contraseña.',
    'auth_password_mismatch_title': 'Contraseñas distintas',
    'auth_password_mismatch_message':
        'La confirmación de contraseña no coincide.',
    'auth_check_email_signup_message':
        'Tu cuenta fue creada. Confirma tu correo antes de iniciar sesión.',
    'auth_create_account_title': 'Crea tu cuenta',
    'auth_create_account_subtitle':
        'Configura tu acceso de WakeApp una vez y úsalo en todos tus dispositivos.',
    'auth_account_details': 'Datos de la cuenta',
    'auth_account_details_subtitle':
        'Elige los datos que usarás para iniciar sesión más tarde.',
    'auth_full_name': 'Nombre completo',
    'auth_your_name': 'Tu nombre',
    'auth_confirm_password_label': 'Confirmar contraseña',
    'auth_confirm_password_placeholder': 'Confirmar contraseña',
    'auth_already_registered': '¿Ya estás registrado?',
    'blackout_prep_intro_title': 'Prepara tu pantalla para Blackout',
    'blackout_prep_intro_body':
        'Algunas apps del sistema siguen visibles en iPhone. Agrúpalas en una carpeta para un Blackout más limpio.',
    'blackout_prep_intro_goal':
        'Objetivo: crear una pantalla de inicio más calmada en menos de 20 segundos.',
    'blackout_prep_demo_title': 'Agrupa apps secundarias durante el focus',
    'blackout_prep_demo_body':
        'FaceTime, Mapas, Archivos, Casa, Buscar… Agrúpalas para reducir el ruido visual.',
    'blackout_prep_demo_primary': 'Optimizar mi pantalla',
    'blackout_prep_checklist_title': 'Hazlo en 20 segundos',
    'blackout_prep_checklist_body': 'Cuando termines, vuelve aquí.',
    'blackout_prep_step_hold_app': 'Mantén pulsada una app',
    'blackout_prep_step_drag_on_other': 'Arrástrala sobre otra',
    'blackout_prep_step_create_folder': 'Crea una carpeta "Fuera de Focus"',
    'blackout_prep_step_add_system_apps':
        'Añade las apps del sistema visibles',
    'blackout_prep_done': 'Listo',
    'blackout_prep_animation_calm_screen': 'Pantalla más calmada',
    'blackout_prep_animation_folder_name': 'Fuera de Focus',
  },
  'pt': {
    'onboarding_step_of': 'Etapa {step} de {total}',
    'onboarding_log_in': 'Entrar',
    'onboarding_enter_wakeapp': 'Entrar no WakeApp',
    'onboarding_adjust_later_settings':
        'Você pode ajustar isso depois em Configurações',
    'onboarding_continue': 'Continuar',
    'onboarding_next': 'Próximo',
    'onboarding_slide_operate_title': 'Opere como um CEO',
    'onboarding_slide_habits_title': 'Construa hábitos compostos',
    'onboarding_slide_focus_title': 'Proteja o trabalho profundo',
    'onboarding_questionnaire_title': 'Inicialize seu sistema',
    'onboarding_questionnaire_subtitle':
        'Defina como você opera antes de entrar no sistema',
    'onboarding_primary_orientation': 'Orientação principal',
    'onboarding_current_level': 'Nível atual',
    'onboarding_main_constraint': 'Principal restrição',
    'onboarding_system_theme': 'Tema do sistema',
    'onboarding_system_profile': 'Perfil do sistema',
    'onboarding_orientation': 'Orientação',
    'onboarding_level': 'Nível',
    'onboarding_constraint': 'Restrição',
    'onboarding_theme': 'Tema',
    'onboarding_goal_execution': 'Execução',
    'onboarding_goal_consistency': 'Consistência',
    'onboarding_goal_focus': 'Foco',
    'onboarding_goal_planning': 'Planejamento',
    'onboarding_level_beginner': 'Iniciante',
    'onboarding_level_intermediate': 'Intermediário',
    'onboarding_level_advanced': 'Avançado',
    'onboarding_constraint_distractions': 'Distrações',
    'onboarding_constraint_overload': 'Sobrecarga',
    'onboarding_constraint_inconsistency': 'Inconsistência',
    'setup_preparing': 'Preparando configuração…',
    'setup_step_of': 'Etapa {step} de {total}',
    'setup_steps_label': '{total} etapas',
    'setup_start': 'Iniciar configuração',
    'setup_continue': 'Continuar',
    'setup_open_settings': 'Abrir ajustes',
    'setup_success_title': 'Tudo pronto',
    'setup_open_screen_time': 'Abrir Screen Time',
    'ios_setup_preparing': 'Preparando Screen Time…',
    'ios_setup_step_1_of_2': 'Etapa 1 de 2',
    'ios_setup_step_2_of_2': 'Etapa 2 de 2',
    'ios_setup_intro_title': 'Configurar Screen Time',
    'ios_setup_start': 'Iniciar configuração',
    'ios_setup_permission_allow_title': 'Permitir acesso ao Screen Time',
    'ios_setup_permission_unavailable_title': 'Screen Time indisponível',
    'ios_setup_steps_title': 'Etapas',
    'ios_setup_instruction_1': 'Toque em "Abrir ajustes".',
    'ios_setup_instruction_2': 'Escolha WakeApp na lista.',
    'ios_setup_instruction_3': 'Ative o acesso ao Screen Time.',
    'ios_setup_instruction_4': 'Volte para o WakeApp.',
    'ios_setup_permission_granted': 'Permissão concedida',
    'ios_setup_access_turned_off': 'Acesso desativado',
    'ios_setup_waiting_approval': 'Aguardando aprovação',
    'ios_setup_completed': 'Concluído',
    'ios_setup_ready_title': 'Screen Time está pronto',
    'ios_setup_next': 'Próximo',
    'ios_setup_open_screen_time': 'Abrir Screen Time',
    'ios_setup_continue': 'Continuar',
    'auth_signin_error_title': 'Erro ao iniciar sessão',
    'auth_invalid_email_title': 'Email inválido',
    'auth_invalid_email_message': 'Insira um endereço de email válido.',
    'auth_password_required_title': 'Senha obrigatória',
    'auth_password_required_message':
        'Insira sua senha para continuar.',
    'auth_reset_password_title': 'Redefinir senha',
    'auth_reset_password_enter_email_first':
        'Digite primeiro o email da conta e tente novamente.',
    'auth_check_email_title': 'Verifique seu email',
    'auth_check_email_reset_message':
        'Se existir uma conta para {email}, um email de redefinição foi enviado.',
    'auth_login_subtitle':
        'Entre para restaurar seu sistema, sincronizar seus dados e continuar de onde parou.',
    'auth_secure_sync': 'Sincronização segura na nuvem entre dispositivos.',
    'auth_sign_in': 'Entrar',
    'auth_use_same_credentials':
        'Use o mesmo email e senha que você criou no WakeApp.',
    'auth_email': 'Email',
    'auth_email_placeholder': 'nome@exemplo.com',
    'auth_password': 'Senha',
    'auth_forgot_password': 'Esqueceu a senha?',
    'auth_new_to_wakeapp': 'Novo no WakeApp?',
    'auth_create_account': 'Criar conta',
    'auth_account_setup_error_title': 'Erro ao criar conta',
    'auth_name_required_title': 'Nome obrigatório',
    'auth_name_required_message': 'Digite seu nome para criar a conta.',
    'auth_weak_password_title': 'Senha fraca',
    'auth_weak_password_message':
        'Use pelo menos 8 caracteres na sua senha.',
    'auth_password_mismatch_title': 'Senhas diferentes',
    'auth_password_mismatch_message':
        'A confirmação de senha não corresponde.',
    'auth_check_email_signup_message':
        'Sua conta foi criada. Confirme seu email antes de entrar.',
    'auth_create_account_title': 'Crie sua conta',
    'auth_create_account_subtitle':
        'Configure o login do WakeApp uma vez e use em todos os seus dispositivos.',
    'auth_account_details': 'Detalhes da conta',
    'auth_account_details_subtitle':
        'Escolha os dados que você usará para entrar depois.',
    'auth_full_name': 'Nome completo',
    'auth_your_name': 'Seu nome',
    'auth_confirm_password_label': 'Confirmar senha',
    'auth_confirm_password_placeholder': 'Confirmar senha',
    'auth_already_registered': 'Já possui cadastro?',
    'blackout_prep_intro_title': 'Prepare sua tela para o Blackout',
    'blackout_prep_intro_body':
        'Alguns apps do sistema continuam visíveis no iPhone. Agrupe-os em uma pasta para um Blackout mais limpo.',
    'blackout_prep_intro_goal':
        'Objetivo: criar uma tela inicial mais calma em menos de 20 segundos.',
    'blackout_prep_demo_title': 'Organize apps secundários durante o foco',
    'blackout_prep_demo_body':
        'FaceTime, Mapas, Arquivos, Casa, Buscar… Agrupe-os para reduzir ruído visual.',
    'blackout_prep_demo_primary': 'Otimizar minha tela',
    'blackout_prep_checklist_title': 'Faça em 20 segundos',
    'blackout_prep_checklist_body': 'Quando terminar, volte aqui.',
    'blackout_prep_step_hold_app': 'Pressione e segure um app',
    'blackout_prep_step_drag_on_other': 'Arraste sobre outro app',
    'blackout_prep_step_create_folder': 'Crie uma pasta "Fora do Foco"',
    'blackout_prep_step_add_system_apps': 'Adicione apps de sistema visíveis',
    'blackout_prep_done': 'Concluído',
    'blackout_prep_animation_calm_screen': 'Tela mais calma',
    'blackout_prep_animation_folder_name': 'Fora do Foco',
  },
  'ru': {
    'onboarding_step_of': 'Шаг {step} из {total}',
    'onboarding_log_in': 'Войти',
    'onboarding_enter_wakeapp': 'Войти в WakeApp',
    'onboarding_adjust_later_settings':
        'Это можно изменить позже в настройках',
    'onboarding_continue': 'Продолжить',
    'onboarding_next': 'Далее',
    'onboarding_slide_operate_title': 'Действуй как CEO',
    'onboarding_slide_habits_title': 'Создавай накопительные привычки',
    'onboarding_slide_focus_title': 'Защити глубокую работу',
    'onboarding_questionnaire_title': 'Инициализируй свою систему',
    'onboarding_questionnaire_subtitle':
        'Определи, как ты работаешь, перед входом в систему',
    'onboarding_primary_orientation': 'Главный вектор',
    'onboarding_current_level': 'Текущий уровень',
    'onboarding_main_constraint': 'Главное ограничение',
    'onboarding_system_theme': 'Тема системы',
    'onboarding_system_profile': 'Профиль системы',
    'onboarding_orientation': 'Вектор',
    'onboarding_level': 'Уровень',
    'onboarding_constraint': 'Ограничение',
    'onboarding_theme': 'Тема',
    'onboarding_goal_execution': 'Исполнение',
    'onboarding_goal_consistency': 'Стабильность',
    'onboarding_goal_focus': 'Фокус',
    'onboarding_goal_planning': 'Планирование',
    'onboarding_level_beginner': 'Начальный',
    'onboarding_level_intermediate': 'Средний',
    'onboarding_level_advanced': 'Продвинутый',
    'onboarding_constraint_distractions': 'Отвлечения',
    'onboarding_constraint_overload': 'Перегрузка',
    'onboarding_constraint_inconsistency': 'Нерегулярность',
    'setup_preparing': 'Подготовка настройки…',
    'setup_step_of': 'Шаг {step} из {total}',
    'setup_steps_label': '{total} шага',
    'setup_start': 'Начать настройку',
    'setup_continue': 'Продолжить',
    'setup_open_settings': 'Открыть настройки',
    'setup_success_title': 'Готово',
    'setup_open_screen_time': 'Открыть Screen Time',
    'ios_setup_preparing': 'Подготовка Screen Time…',
    'ios_setup_step_1_of_2': 'Шаг 1 из 2',
    'ios_setup_step_2_of_2': 'Шаг 2 из 2',
    'ios_setup_intro_title': 'Настроить Screen Time',
    'ios_setup_start': 'Начать настройку',
    'ios_setup_permission_allow_title': 'Разрешить доступ к Screen Time',
    'ios_setup_permission_unavailable_title': 'Screen Time недоступен',
    'ios_setup_steps_title': 'Шаги',
    'ios_setup_instruction_1': 'Нажмите «Открыть настройки».',
    'ios_setup_instruction_2': 'Выберите WakeApp в списке.',
    'ios_setup_instruction_3': 'Включите доступ Screen Time.',
    'ios_setup_instruction_4': 'Вернитесь в WakeApp.',
    'ios_setup_permission_granted': 'Разрешение выдано',
    'ios_setup_access_turned_off': 'Доступ отключён',
    'ios_setup_waiting_approval': 'Ожидание подтверждения',
    'ios_setup_completed': 'Завершено',
    'ios_setup_ready_title': 'Screen Time готов',
    'ios_setup_next': 'Далее',
    'ios_setup_open_screen_time': 'Открыть Screen Time',
    'ios_setup_continue': 'Продолжить',
    'auth_signin_error_title': 'Ошибка входа',
    'auth_invalid_email_title': 'Неверный email',
    'auth_invalid_email_message': 'Введите корректный адрес email.',
    'auth_password_required_title': 'Требуется пароль',
    'auth_password_required_message': 'Введите пароль, чтобы продолжить.',
    'auth_reset_password_title': 'Сброс пароля',
    'auth_reset_password_enter_email_first':
        'Сначала введите email аккаунта, затем попробуйте снова.',
    'auth_check_email_title': 'Проверьте почту',
    'auth_check_email_reset_message':
        'Если аккаунт для {email} существует, письмо для сброса пароля отправлено.',
    'auth_login_subtitle':
        'Войдите, чтобы восстановить систему, синхронизировать данные и продолжить с того места, где вы остановились.',
    'auth_secure_sync': 'Безопасная облачная синхронизация между устройствами.',
    'auth_sign_in': 'Войти',
    'auth_use_same_credentials':
        'Используйте тот же email и пароль, что вы создали в WakeApp.',
    'auth_email': 'Email',
    'auth_email_placeholder': 'name@example.com',
    'auth_password': 'Пароль',
    'auth_forgot_password': 'Забыли пароль?',
    'auth_new_to_wakeapp': 'Впервые в WakeApp?',
    'auth_create_account': 'Создать аккаунт',
    'auth_account_setup_error_title': 'Ошибка создания аккаунта',
    'auth_name_required_title': 'Требуется имя',
    'auth_name_required_message': 'Введите имя, чтобы создать аккаунт.',
    'auth_weak_password_title': 'Слабый пароль',
    'auth_weak_password_message':
        'Используйте не менее 8 символов в пароле.',
    'auth_password_mismatch_title': 'Пароли не совпадают',
    'auth_password_mismatch_message':
        'Подтверждение пароля не совпадает.',
    'auth_check_email_signup_message':
        'Аккаунт создан. Подтвердите email перед входом.',
    'auth_create_account_title': 'Создайте аккаунт',
    'auth_create_account_subtitle':
        'Настройте вход в WakeApp один раз и используйте его на всех устройствах.',
    'auth_account_details': 'Данные аккаунта',
    'auth_account_details_subtitle':
        'Выберите данные, которые будете использовать для входа позже.',
    'auth_full_name': 'Полное имя',
    'auth_your_name': 'Ваше имя',
    'auth_confirm_password_label': 'Подтвердите пароль',
    'auth_confirm_password_placeholder': 'Подтвердите пароль',
    'auth_already_registered': 'Уже зарегистрированы?',
    'blackout_prep_intro_title': 'Подготовьте экран к Blackout',
    'blackout_prep_intro_body':
        'Некоторые системные приложения остаются видимыми на iPhone. Сгруппируйте их в папку для более чистого Blackout.',
    'blackout_prep_intro_goal':
        'Цель: сделать домашний экран спокойнее менее чем за 20 секунд.',
    'blackout_prep_demo_title': 'Сгруппируйте вторичные приложения во время фокуса',
    'blackout_prep_demo_body':
        'FaceTime, Карты, Файлы, Дом, Локатор… Сгруппируйте их, чтобы снизить визуальный шум.',
    'blackout_prep_demo_primary': 'Оптимизировать экран',
    'blackout_prep_checklist_title': 'Сделайте это за 20 секунд',
    'blackout_prep_checklist_body': 'Когда закончите, вернитесь сюда.',
    'blackout_prep_step_hold_app': 'Удерживайте иконку приложения',
    'blackout_prep_step_drag_on_other': 'Перетащите на другое приложение',
    'blackout_prep_step_create_folder': 'Создайте папку «Вне фокуса»',
    'blackout_prep_step_add_system_apps':
        'Добавьте видимые системные приложения',
    'blackout_prep_done': 'Готово',
    'blackout_prep_animation_calm_screen': 'Экран спокойнее',
    'blackout_prep_animation_folder_name': 'Вне фокуса',
  },
  'ar': {
    'onboarding_step_of': 'الخطوة {step} من {total}',
    'onboarding_log_in': 'تسجيل الدخول',
    'onboarding_enter_wakeapp': 'الدخول إلى WakeApp',
    'onboarding_adjust_later_settings':
        'يمكنك تعديل ذلك لاحقًا من الإعدادات',
    'onboarding_continue': 'متابعة',
    'onboarding_next': 'التالي',
    'onboarding_slide_operate_title': 'اعمل بعقلية CEO',
    'onboarding_slide_habits_title': 'ابنِ عادات تراكمية',
    'onboarding_slide_focus_title': 'احمِ العمل العميق',
    'onboarding_questionnaire_title': 'هيّئ نظامك',
    'onboarding_questionnaire_subtitle':
        'حدّد طريقة عملك قبل دخول النظام',
    'onboarding_primary_orientation': 'التوجّه الأساسي',
    'onboarding_current_level': 'المستوى الحالي',
    'onboarding_main_constraint': 'القيد الرئيسي',
    'onboarding_system_theme': 'سمة النظام',
    'onboarding_system_profile': 'ملف النظام',
    'onboarding_orientation': 'التوجّه',
    'onboarding_level': 'المستوى',
    'onboarding_constraint': 'القيد',
    'onboarding_theme': 'السمة',
    'onboarding_goal_execution': 'التنفيذ',
    'onboarding_goal_consistency': 'الاستمرارية',
    'onboarding_goal_focus': 'التركيز',
    'onboarding_goal_planning': 'التخطيط',
    'onboarding_level_beginner': 'مبتدئ',
    'onboarding_level_intermediate': 'متوسط',
    'onboarding_level_advanced': 'متقدم',
    'onboarding_constraint_distractions': 'المشتتات',
    'onboarding_constraint_overload': 'الضغط الزائد',
    'onboarding_constraint_inconsistency': 'عدم الانتظام',
    'setup_preparing': 'جارٍ تجهيز الإعداد…',
    'setup_step_of': 'الخطوة {step} من {total}',
    'setup_steps_label': '{total} خطوات',
    'setup_start': 'بدء الإعداد',
    'setup_continue': 'متابعة',
    'setup_open_settings': 'فتح الإعدادات',
    'setup_success_title': 'تم الإعداد',
    'setup_open_screen_time': 'فتح Screen Time',
    'ios_setup_preparing': 'جارٍ تجهيز Screen Time…',
    'ios_setup_step_1_of_2': 'الخطوة 1 من 2',
    'ios_setup_step_2_of_2': 'الخطوة 2 من 2',
    'ios_setup_intro_title': 'إعداد Screen Time',
    'ios_setup_start': 'بدء الإعداد',
    'ios_setup_permission_allow_title': 'السماح بوصول Screen Time',
    'ios_setup_permission_unavailable_title': 'Screen Time غير متاح',
    'ios_setup_steps_title': 'الخطوات',
    'ios_setup_instruction_1': 'اضغط على «فتح الإعدادات».',
    'ios_setup_instruction_2': 'اختر WakeApp من القائمة.',
    'ios_setup_instruction_3': 'فعّل وصول Screen Time.',
    'ios_setup_instruction_4': 'ارجع إلى WakeApp.',
    'ios_setup_permission_granted': 'تم منح الإذن',
    'ios_setup_access_turned_off': 'تم إيقاف الوصول',
    'ios_setup_waiting_approval': 'بانتظار الموافقة',
    'ios_setup_completed': 'مكتمل',
    'ios_setup_ready_title': 'Screen Time جاهز',
    'ios_setup_next': 'التالي',
    'ios_setup_open_screen_time': 'فتح Screen Time',
    'ios_setup_continue': 'متابعة',
    'auth_signin_error_title': 'خطأ في تسجيل الدخول',
    'auth_invalid_email_title': 'بريد إلكتروني غير صالح',
    'auth_invalid_email_message':
        'يرجى إدخال عنوان بريد إلكتروني صالح.',
    'auth_password_required_title': 'كلمة المرور مطلوبة',
    'auth_password_required_message':
        'يرجى إدخال كلمة المرور للمتابعة.',
    'auth_reset_password_title': 'إعادة تعيين كلمة المرور',
    'auth_reset_password_enter_email_first':
        'أدخل بريد حسابك أولاً ثم حاول مرة أخرى.',
    'auth_check_email_title': 'تحقق من بريدك',
    'auth_check_email_reset_message':
        'إذا كان هناك حساب لـ {email} فسيتم إرسال رسالة إعادة تعيين كلمة المرور.',
    'auth_login_subtitle':
        'سجّل الدخول لاستعادة نظامك ومزامنة بياناتك والمتابعة من حيث توقفت.',
    'auth_secure_sync': 'مزامنة سحابية آمنة عبر أجهزتك.',
    'auth_sign_in': 'تسجيل الدخول',
    'auth_use_same_credentials':
        'استخدم نفس البريد وكلمة المرور التي أنشأتها في WakeApp.',
    'auth_email': 'البريد الإلكتروني',
    'auth_email_placeholder': 'name@example.com',
    'auth_password': 'كلمة المرور',
    'auth_forgot_password': 'هل نسيت كلمة المرور؟',
    'auth_new_to_wakeapp': 'جديد على WakeApp؟',
    'auth_create_account': 'إنشاء حساب',
    'auth_account_setup_error_title': 'خطأ في إعداد الحساب',
    'auth_name_required_title': 'الاسم مطلوب',
    'auth_name_required_message': 'يرجى إدخال اسمك لإنشاء الحساب.',
    'auth_weak_password_title': 'كلمة مرور ضعيفة',
    'auth_weak_password_message':
        'استخدم 8 أحرف على الأقل في كلمة المرور.',
    'auth_password_mismatch_title': 'كلمتا المرور غير متطابقتين',
    'auth_password_mismatch_message':
        'تأكيد كلمة المرور غير مطابق.',
    'auth_check_email_signup_message':
        'تم إنشاء حسابك. يرجى تأكيد بريدك الإلكتروني قبل تسجيل الدخول.',
    'auth_create_account_title': 'أنشئ حسابك',
    'auth_create_account_subtitle':
        'قم بإعداد تسجيل دخول WakeApp مرة واحدة ثم استخدمه على جميع أجهزتك.',
    'auth_account_details': 'تفاصيل الحساب',
    'auth_account_details_subtitle':
        'اختر البيانات التي ستستخدمها لتسجيل الدخول لاحقًا.',
    'auth_full_name': 'الاسم الكامل',
    'auth_your_name': 'اسمك',
    'auth_confirm_password_label': 'تأكيد كلمة المرور',
    'auth_confirm_password_placeholder': 'تأكيد كلمة المرور',
    'auth_already_registered': 'لديك حساب بالفعل؟',
    'blackout_prep_intro_title': 'جهّز شاشتك لوضع Blackout',
    'blackout_prep_intro_body':
        'بعض تطبيقات النظام تبقى مرئية على iPhone. اجمعها في مجلد للحصول على Blackout أنظف.',
    'blackout_prep_intro_goal':
        'الهدف: إنشاء شاشة رئيسية أكثر هدوءًا في أقل من 20 ثانية.',
    'blackout_prep_demo_title': 'رتّب التطبيقات الثانوية أثناء التركيز',
    'blackout_prep_demo_body':
        'FaceTime وخرائط وملفات والمنزل والعثور على… اجمعها لتقليل الضجيج البصري.',
    'blackout_prep_demo_primary': 'تحسين شاشتي',
    'blackout_prep_checklist_title': 'أنجزها في 20 ثانية',
    'blackout_prep_checklist_body': 'عند الانتهاء، عُد إلى هنا.',
    'blackout_prep_step_hold_app': 'اضغط مطولًا على تطبيق',
    'blackout_prep_step_drag_on_other': 'اسحبه فوق تطبيق آخر',
    'blackout_prep_step_create_folder': 'أنشئ مجلدًا باسم «خارج التركيز»',
    'blackout_prep_step_add_system_apps':
        'أضف تطبيقات النظام الظاهرة إلى المجلد',
    'blackout_prep_done': 'تم',
    'blackout_prep_animation_calm_screen': 'شاشة أكثر هدوءًا',
    'blackout_prep_animation_folder_name': 'خارج التركيز',
  },
  'id': {
    'onboarding_step_of': 'Langkah {step} dari {total}',
    'onboarding_log_in': 'Masuk',
    'onboarding_enter_wakeapp': 'Masuk ke WakeApp',
    'onboarding_adjust_later_settings':
        'Kamu bisa mengubah ini nanti di Pengaturan',
    'onboarding_continue': 'Lanjut',
    'onboarding_next': 'Berikutnya',
    'onboarding_slide_operate_title': 'Beroperasi seperti CEO',
    'onboarding_slide_habits_title': 'Bangun kebiasaan yang bertumbuh',
    'onboarding_slide_focus_title': 'Lindungi deep work',
    'onboarding_questionnaire_title': 'Inisialisasi sistemmu',
    'onboarding_questionnaire_subtitle':
        'Tentukan cara kerjamu sebelum masuk ke sistem',
    'onboarding_primary_orientation': 'Orientasi utama',
    'onboarding_current_level': 'Level saat ini',
    'onboarding_main_constraint': 'Kendala utama',
    'onboarding_system_theme': 'Tema sistem',
    'onboarding_system_profile': 'Profil sistem',
    'onboarding_orientation': 'Orientasi',
    'onboarding_level': 'Level',
    'onboarding_constraint': 'Kendala',
    'onboarding_theme': 'Tema',
    'onboarding_goal_execution': 'Eksekusi',
    'onboarding_goal_consistency': 'Konsistensi',
    'onboarding_goal_focus': 'Fokus',
    'onboarding_goal_planning': 'Perencanaan',
    'onboarding_level_beginner': 'Pemula',
    'onboarding_level_intermediate': 'Menengah',
    'onboarding_level_advanced': 'Lanjutan',
    'onboarding_constraint_distractions': 'Gangguan',
    'onboarding_constraint_overload': 'Kelebihan beban',
    'onboarding_constraint_inconsistency': 'Tidak konsisten',
    'setup_preparing': 'Menyiapkan pengaturan…',
    'setup_step_of': 'Langkah {step} dari {total}',
    'setup_steps_label': '{total} langkah',
    'setup_start': 'Mulai pengaturan',
    'setup_continue': 'Lanjut',
    'setup_open_settings': 'Buka pengaturan',
    'setup_success_title': 'Semua siap',
    'setup_open_screen_time': 'Buka Screen Time',
    'ios_setup_preparing': 'Menyiapkan Screen Time…',
    'ios_setup_step_1_of_2': 'Langkah 1 dari 2',
    'ios_setup_step_2_of_2': 'Langkah 2 dari 2',
    'ios_setup_intro_title': 'Atur Screen Time',
    'ios_setup_start': 'Mulai pengaturan',
    'ios_setup_permission_allow_title': 'Izinkan akses Screen Time',
    'ios_setup_permission_unavailable_title': 'Screen Time tidak tersedia',
    'ios_setup_steps_title': 'Langkah',
    'ios_setup_instruction_1': 'Ketuk "Buka Pengaturan".',
    'ios_setup_instruction_2': 'Pilih WakeApp di daftar.',
    'ios_setup_instruction_3': 'Aktifkan akses Screen Time.',
    'ios_setup_instruction_4': 'Kembali ke WakeApp.',
    'ios_setup_permission_granted': 'Izin diberikan',
    'ios_setup_access_turned_off': 'Akses dimatikan',
    'ios_setup_waiting_approval': 'Menunggu persetujuan',
    'ios_setup_completed': 'Selesai',
    'ios_setup_ready_title': 'Screen Time siap',
    'ios_setup_next': 'Berikutnya',
    'ios_setup_open_screen_time': 'Buka Screen Time',
    'ios_setup_continue': 'Lanjut',
    'auth_signin_error_title': 'Kesalahan masuk',
    'auth_invalid_email_title': 'Email tidak valid',
    'auth_invalid_email_message': 'Masukkan alamat email yang valid.',
    'auth_password_required_title': 'Kata sandi wajib diisi',
    'auth_password_required_message':
        'Masukkan kata sandi untuk melanjutkan.',
    'auth_reset_password_title': 'Atur ulang kata sandi',
    'auth_reset_password_enter_email_first':
        'Masukkan email akun terlebih dahulu, lalu coba lagi.',
    'auth_check_email_title': 'Periksa email kamu',
    'auth_check_email_reset_message':
        'Jika ada akun untuk {email}, email reset kata sandi telah dikirim.',
    'auth_login_subtitle':
        'Masuk untuk memulihkan sistemmu, sinkronkan data, dan lanjutkan dari titik terakhir.',
    'auth_secure_sync': 'Sinkronisasi cloud aman di semua perangkat.',
    'auth_sign_in': 'Masuk',
    'auth_use_same_credentials':
        'Gunakan email dan kata sandi yang sama seperti saat membuat WakeApp.',
    'auth_email': 'Email',
    'auth_email_placeholder': 'nama@contoh.com',
    'auth_password': 'Kata sandi',
    'auth_forgot_password': 'Lupa kata sandi?',
    'auth_new_to_wakeapp': 'Baru di WakeApp?',
    'auth_create_account': 'Buat akun',
    'auth_account_setup_error_title': 'Kesalahan pembuatan akun',
    'auth_name_required_title': 'Nama wajib diisi',
    'auth_name_required_message': 'Masukkan nama untuk membuat akun.',
    'auth_weak_password_title': 'Kata sandi lemah',
    'auth_weak_password_message':
        'Gunakan minimal 8 karakter untuk kata sandi.',
    'auth_password_mismatch_title': 'Kata sandi tidak cocok',
    'auth_password_mismatch_message':
        'Konfirmasi kata sandi tidak cocok.',
    'auth_check_email_signup_message':
        'Akun kamu berhasil dibuat. Konfirmasi email sebelum masuk.',
    'auth_create_account_title': 'Buat akunmu',
    'auth_create_account_subtitle':
        'Atur login WakeApp sekali, lalu gunakan di semua perangkat.',
    'auth_account_details': 'Detail akun',
    'auth_account_details_subtitle':
        'Pilih detail yang akan kamu gunakan untuk masuk nanti.',
    'auth_full_name': 'Nama lengkap',
    'auth_your_name': 'Namamu',
    'auth_confirm_password_label': 'Konfirmasi kata sandi',
    'auth_confirm_password_placeholder': 'Konfirmasi kata sandi',
    'auth_already_registered': 'Sudah terdaftar?',
    'blackout_prep_intro_title': 'Siapkan layar untuk Blackout',
    'blackout_prep_intro_body':
        'Beberapa aplikasi sistem tetap terlihat di iPhone. Kelompokkan ke satu folder untuk Blackout yang lebih bersih.',
    'blackout_prep_intro_goal':
        'Tujuan: membuat Home Screen lebih tenang dalam kurang dari 20 detik.',
    'blackout_prep_demo_title': 'Rapikan aplikasi sekunder saat fokus',
    'blackout_prep_demo_body':
        'FaceTime, Maps, Files, Home, Find My… Kelompokkan agar gangguan visual berkurang.',
    'blackout_prep_demo_primary': 'Optimalkan layarku',
    'blackout_prep_checklist_title': 'Lakukan dalam 20 detik',
    'blackout_prep_checklist_body': 'Setelah selesai, kembali ke sini.',
    'blackout_prep_step_hold_app': 'Tekan dan tahan ikon aplikasi',
    'blackout_prep_step_drag_on_other': 'Seret ke atas aplikasi lain',
    'blackout_prep_step_create_folder': 'Buat folder bernama "Di Luar Fokus"',
    'blackout_prep_step_add_system_apps':
        'Masukkan aplikasi sistem yang terlihat',
    'blackout_prep_done': 'Selesai',
    'blackout_prep_animation_calm_screen': 'Layar lebih tenang',
    'blackout_prep_animation_folder_name': 'Di Luar Fokus',
  },
  'hi': {
    'language_not_available': 'उपलब्ध नहीं',
    'onboarding_step_of': 'चरण {step} / {total}',
    'onboarding_log_in': 'लॉग इन',
    'onboarding_enter_wakeapp': 'WakeApp में प्रवेश करें',
    'onboarding_adjust_later_settings':
        'इसे बाद में सेटिंग्स में बदला जा सकता है',
    'onboarding_continue': 'जारी रखें',
    'onboarding_next': 'अगला',
    'onboarding_slide_operate_title': 'CEO की तरह काम करें',
    'onboarding_slide_habits_title': 'कंपाउंडिंग आदतें बनाएं',
    'onboarding_slide_focus_title': 'डीप वर्क सुरक्षित रखें',
    'onboarding_questionnaire_title': 'अपना सिस्टम प्रारंभ करें',
    'onboarding_questionnaire_subtitle':
        'सिस्टम में प्रवेश से पहले अपनी कार्य शैली तय करें',
    'onboarding_primary_orientation': 'मुख्य दिशा',
    'onboarding_current_level': 'वर्तमान स्तर',
    'onboarding_main_constraint': 'मुख्य बाधा',
    'onboarding_system_theme': 'सिस्टम थीम',
    'onboarding_system_profile': 'सिस्टम प्रोफ़ाइल',
    'onboarding_orientation': 'दिशा',
    'onboarding_level': 'स्तर',
    'onboarding_constraint': 'बाधा',
    'onboarding_theme': 'थीम',
    'onboarding_goal_execution': 'एक्ज़िक्यूशन',
    'onboarding_goal_consistency': 'निरंतरता',
    'onboarding_goal_focus': 'फोकस',
    'onboarding_goal_planning': 'योजना',
    'onboarding_level_beginner': 'शुरुआती',
    'onboarding_level_intermediate': 'मध्यम',
    'onboarding_level_advanced': 'उन्नत',
    'onboarding_constraint_distractions': 'ध्यान भंग',
    'onboarding_constraint_overload': 'अत्यधिक दबाव',
    'onboarding_constraint_inconsistency': 'असंगति',
    'setup_preparing': 'सेटअप तैयार हो रहा है…',
    'setup_step_of': 'चरण {step} / {total}',
    'setup_steps_label': '{total} चरण',
    'setup_start': 'सेटअप शुरू करें',
    'setup_continue': 'जारी रखें',
    'setup_open_settings': 'सेटिंग्स खोलें',
    'setup_success_title': 'सब तैयार है',
    'setup_open_screen_time': 'Screen Time खोलें',
    'ios_setup_preparing': 'Screen Time तैयार हो रहा है…',
    'ios_setup_step_1_of_2': 'चरण 1 / 2',
    'ios_setup_step_2_of_2': 'चरण 2 / 2',
    'ios_setup_intro_title': 'Screen Time सेट करें',
    'ios_setup_start': 'सेटअप शुरू करें',
    'ios_setup_permission_allow_title': 'Screen Time एक्सेस अनुमति दें',
    'ios_setup_permission_unavailable_title': 'Screen Time उपलब्ध नहीं',
    'ios_setup_steps_title': 'चरण',
    'ios_setup_instruction_1': '"Open Settings" पर टैप करें।',
    'ios_setup_instruction_2': 'सूची में WakeApp चुनें।',
    'ios_setup_instruction_3': 'Screen Time एक्सेस सक्षम करें।',
    'ios_setup_instruction_4': 'WakeApp पर वापस आएँ।',
    'ios_setup_permission_granted': 'अनुमति मिल गई',
    'ios_setup_access_turned_off': 'एक्सेस बंद है',
    'ios_setup_waiting_approval': 'स्वीकृति की प्रतीक्षा',
    'ios_setup_completed': 'पूर्ण',
    'ios_setup_ready_title': 'Screen Time तैयार है',
    'ios_setup_next': 'अगला',
    'ios_setup_open_screen_time': 'Screen Time खोलें',
    'ios_setup_continue': 'जारी रखें',
    'auth_signin_error_title': 'साइन-इन त्रुटि',
    'auth_invalid_email_title': 'अमान्य ईमेल',
    'auth_invalid_email_message': 'कृपया मान्य ईमेल पता दर्ज करें।',
    'auth_password_required_title': 'पासवर्ड आवश्यक है',
    'auth_password_required_message': 'जारी रखने के लिए पासवर्ड दर्ज करें।',
    'auth_reset_password_title': 'पासवर्ड रीसेट करें',
    'auth_reset_password_enter_email_first':
        'पहले अपना अकाउंट ईमेल दर्ज करें, फिर दोबारा प्रयास करें।',
    'auth_check_email_title': 'अपना ईमेल देखें',
    'auth_check_email_reset_message':
        'यदि {email} के लिए अकाउंट मौजूद है, तो पासवर्ड रीसेट ईमेल भेज दिया गया है।',
    'auth_login_subtitle':
        'अपने सिस्टम को बहाल करने, डेटा सिंक करने और जहाँ छोड़ा था वहीं से जारी रखने के लिए साइन-इन करें।',
    'auth_secure_sync': 'आपके सभी डिवाइस पर सुरक्षित क्लाउड सिंक।',
    'auth_sign_in': 'साइन-इन',
    'auth_use_same_credentials':
        'WakeApp पर बनाया गया वही ईमेल और पासवर्ड उपयोग करें।',
    'auth_email': 'ईमेल',
    'auth_email_placeholder': 'name@example.com',
    'auth_password': 'पासवर्ड',
    'auth_forgot_password': 'पासवर्ड भूल गए?',
    'auth_new_to_wakeapp': 'WakeApp पर नए हैं?',
    'auth_create_account': 'अकाउंट बनाएँ',
    'auth_account_setup_error_title': 'अकाउंट सेटअप त्रुटि',
    'auth_name_required_title': 'नाम आवश्यक है',
    'auth_name_required_message':
        'अकाउंट बनाने के लिए कृपया अपना नाम दर्ज करें।',
    'auth_weak_password_title': 'कमज़ोर पासवर्ड',
    'auth_weak_password_message': 'पासवर्ड में कम से कम 8 अक्षर रखें।',
    'auth_password_mismatch_title': 'पासवर्ड मेल नहीं खाता',
    'auth_password_mismatch_message': 'पासवर्ड पुष्टि मेल नहीं खाती।',
    'auth_check_email_signup_message':
        'आपका अकाउंट बन गया है। साइन-इन से पहले ईमेल पुष्टि करें।',
    'auth_create_account_title': 'अपना अकाउंट बनाएँ',
    'auth_create_account_subtitle':
        'WakeApp लॉगिन एक बार सेट करें, फिर सभी डिवाइस पर उपयोग करें।',
    'auth_account_details': 'अकाउंट विवरण',
    'auth_account_details_subtitle':
        'वे विवरण चुनें जिन्हें आप बाद में साइन-इन के लिए उपयोग करेंगे।',
    'auth_full_name': 'पूरा नाम',
    'auth_your_name': 'आपका नाम',
    'auth_confirm_password_label': 'पासवर्ड की पुष्टि करें',
    'auth_confirm_password_placeholder': 'पासवर्ड की पुष्टि करें',
    'auth_already_registered': 'पहले से रजिस्टर्ड हैं?',
    'blackout_prep_intro_title': 'Blackout के लिए स्क्रीन तैयार करें',
    'blackout_prep_intro_body':
        'iPhone पर कुछ सिस्टम ऐप्स दिखाई देते रहते हैं। साफ़ Blackout के लिए उन्हें एक फ़ोल्डर में रखें।',
    'blackout_prep_intro_goal':
        'लक्ष्य: 20 सेकंड से कम में अधिक शांत होम स्क्रीन बनाना।',
    'blackout_prep_demo_title': 'फोकस के दौरान सेकेंडरी ऐप्स समेटें',
    'blackout_prep_demo_body':
        'FaceTime, Maps, Files, Home, Find My… विज़ुअल शोर कम करने के लिए इन्हें समूह में रखें।',
    'blackout_prep_demo_primary': 'मेरी स्क्रीन ऑप्टिमाइज़ करें',
    'blackout_prep_checklist_title': 'इसे 20 सेकंड में करें',
    'blackout_prep_checklist_body': 'पूरा होने पर यहाँ वापस आएँ।',
    'blackout_prep_step_hold_app': 'किसी ऐप आइकन को दबाकर रखें',
    'blackout_prep_step_drag_on_other': 'उसे दूसरे ऐप पर खींचें',
    'blackout_prep_step_create_folder': '"फोकस से बाहर" नाम का फ़ोल्डर बनाएँ',
    'blackout_prep_step_add_system_apps':
        'दिखने वाले सिस्टम ऐप्स उस फ़ोल्डर में जोड़ें',
    'blackout_prep_done': 'हो गया',
    'blackout_prep_animation_calm_screen': 'अधिक शांत स्क्रीन',
    'blackout_prep_animation_folder_name': 'फोकस से बाहर',
  },
  'zh': {
    'language_not_available': '暂不可用',
    'onboarding_step_of': '第 {step} 步 / 共 {total} 步',
    'onboarding_log_in': '登录',
    'onboarding_enter_wakeapp': '进入觉醒应用',
    'onboarding_adjust_later_settings': '你可以稍后在设置中调整',
    'onboarding_continue': '继续',
    'onboarding_next': '下一步',
    'onboarding_slide_operate_title': '像 CEO 一样执行',
    'onboarding_slide_habits_title': '建立复利习惯',
    'onboarding_slide_focus_title': '保护深度工作',
    'onboarding_questionnaire_title': '初始化你的系统',
    'onboarding_questionnaire_subtitle': '进入系统前先定义你的执行方式',
    'onboarding_primary_orientation': '主要方向',
    'onboarding_current_level': '当前等级',
    'onboarding_main_constraint': '主要限制',
    'onboarding_system_theme': '系统主题',
    'onboarding_system_profile': '系统档案',
    'onboarding_orientation': '方向',
    'onboarding_level': '等级',
    'onboarding_constraint': '限制',
    'onboarding_theme': '主题',
    'onboarding_goal_execution': '执行',
    'onboarding_goal_consistency': '稳定性',
    'onboarding_goal_focus': '专注',
    'onboarding_goal_planning': '规划',
    'onboarding_level_beginner': '初级',
    'onboarding_level_intermediate': '中级',
    'onboarding_level_advanced': '高级',
    'onboarding_constraint_distractions': '干扰',
    'onboarding_constraint_overload': '过载',
    'onboarding_constraint_inconsistency': '不稳定',
    'setup_preparing': '正在准备设置…',
    'setup_step_of': '第 {step} 步 / 共 {total} 步',
    'setup_steps_label': '{total} 个步骤',
    'setup_start': '开始设置',
    'setup_continue': '继续',
    'setup_open_settings': '打开设置',
    'setup_success_title': '设置完成',
    'setup_open_screen_time': '打开屏幕使用时间',
    'ios_setup_preparing': '正在准备屏幕使用时间…',
    'ios_setup_step_1_of_2': '第 1 步 / 共 2 步',
    'ios_setup_step_2_of_2': '第 2 步 / 共 2 步',
    'ios_setup_intro_title': '设置屏幕使用时间',
    'ios_setup_start': '开始设置',
    'ios_setup_permission_allow_title': '允许屏幕使用时间权限',
    'ios_setup_permission_unavailable_title': '屏幕使用时间不可用',
    'ios_setup_steps_title': '步骤',
    'ios_setup_instruction_1': '点击"打开设置"。',
    'ios_setup_instruction_2': '在列表中选择觉醒应用。',
    'ios_setup_instruction_3': '开启屏幕使用时间访问权限。',
    'ios_setup_instruction_4': '返回觉醒应用。',
    'ios_setup_permission_granted': '权限已授予',
    'ios_setup_access_turned_off': '权限已关闭',
    'ios_setup_waiting_approval': '等待授权',
    'ios_setup_completed': '已完成',
    'ios_setup_ready_title': '屏幕使用时间已就绪',
    'ios_setup_next': '下一步',
    'ios_setup_open_screen_time': '打开屏幕使用时间',
    'ios_setup_continue': '继续',
    'auth_signin_error_title': '登录错误',
    'auth_invalid_email_title': '邮箱无效',
    'auth_invalid_email_message': '请输入有效的邮箱地址。',
    'auth_password_required_title': '需要密码',
    'auth_password_required_message': '请输入密码后继续。',
    'auth_reset_password_title': '重置密码',
    'auth_reset_password_enter_email_first':
        '请先输入账户邮箱，再重试。',
    'auth_check_email_title': '请检查邮箱',
    'auth_check_email_reset_message':
        '如果 {email} 对应的账户存在，重置密码邮件已发送。',
    'auth_login_subtitle':
        '登录以恢复你的系统、同步数据，并从上次中断处继续。',
    'auth_secure_sync': '在你的设备间进行安全云同步。',
    'auth_sign_in': '登录',
    'auth_use_same_credentials':
        '使用你在 WakeApp 创建的同一邮箱和密码。',
    'auth_email': '邮箱',
    'auth_email_placeholder': 'name@example.com',
    'auth_password': '密码',
    'auth_forgot_password': '忘记密码？',
    'auth_new_to_wakeapp': '第一次使用觉醒应用？',
    'auth_create_account': '创建账户',
    'auth_account_setup_error_title': '账户创建错误',
    'auth_name_required_title': '需要姓名',
    'auth_name_required_message': '请填写姓名以创建账户。',
    'auth_weak_password_title': '密码过弱',
    'auth_weak_password_message': '密码至少需要 8 个字符。',
    'auth_password_mismatch_title': '密码不一致',
    'auth_password_mismatch_message': '密码确认不匹配。',
    'auth_check_email_signup_message':
        '账户已创建。登录前请先完成邮箱验证。',
    'auth_create_account_title': '创建你的账户',
    'auth_create_account_subtitle':
        '只需一次设置 WakeApp 登录，随后可在所有设备使用。',
    'auth_account_details': '账户信息',
    'auth_account_details_subtitle': '选择你稍后登录时要使用的信息。',
    'auth_full_name': '姓名',
    'auth_your_name': '你的姓名',
    'auth_confirm_password_label': '确认密码',
    'auth_confirm_password_placeholder': '确认密码',
    'auth_already_registered': '已经注册？',
    'blackout_prep_intro_title': '为 Blackout 准备你的主屏幕',
    'blackout_prep_intro_body':
        'iPhone 上部分系统应用仍可见。把它们放进同一个文件夹，让 Blackout 更干净。',
    'blackout_prep_intro_goal': '目标：在 20 秒内让主屏幕更安静。',
    'blackout_prep_demo_title': '专注时整理次要应用',
    'blackout_prep_demo_body':
        'FaceTime、地图、文件、家庭、查找… 将它们分组以降低视觉干扰。',
    'blackout_prep_demo_primary': '优化我的主屏幕',
    'blackout_prep_checklist_title': '20 秒内完成',
    'blackout_prep_checklist_body': '完成后回到这里。',
    'blackout_prep_step_hold_app': '长按一个应用图标',
    'blackout_prep_step_drag_on_other': '将它拖到另一个应用上',
    'blackout_prep_step_create_folder': '创建名为"专注外"的文件夹',
    'blackout_prep_step_add_system_apps': '把可见的系统应用加入该文件夹',
    'blackout_prep_done': '完成',
    'blackout_prep_animation_calm_screen': '更安静的屏幕',
    'blackout_prep_animation_folder_name': '专注外',
  },
};
