import { createContext, useContext, useState, useEffect } from 'react';

const translations = {
  en: {
    // Navigation & Common
    home: "Home",
    back: "Back",
    loading: "Loading",
    save: "Save",
    cancel: "Cancel",
    delete: "Delete",
    edit: "Edit",
    add: "Add",
    confirm: "Confirm",
    close: "Close",
    
    // Home Page
    rank: "Rank",
    streak: "Streak",
    habits: "Habits",
    today: "Today",
    dashboard: "Dashboard",
    yourDailyControlCenter: "Your daily control center",
    actionRequired: "ACTION REQUIRED",
    yesterdayUnvalidated: "Yesterday unvalidated",
    todo: "To-Do",
    schedule: "Schedule",
    screenTime: "Screen Time",
    ceoMode: "CEO Mode",
    maximumFocus: "Maximum Focus",
    
    // Menu
    sixMonthReport: "6-Month Report",
    yourProgressOverview: "Your progress overview",
    activeApps: "Active Apps",
    settingsAndLegal: "Settings & Legal",
    privacyPolicy: "Privacy Policy",
    termsAndConditions: "Terms & conditions",
    logout: "Logout",
    
    // Dashboard
    controlCenter: "Control Center",
    todaysFocus: "Today's Focus",
    weekScore: "WEEK SCORE",
    percent: "Percent",
    target: "Target",
    complete: "Complete",
    youMayExit: "You may exit",
    remaining: "Remaining",
    locked: "LOCKED",
    cannotExitEarly: "Cannot exit early",
    
    // Habits
    habit: "Habit",
    goal: "Goal",
    newHabit: "New Habit",
    addHabit: "Add Habit",
    habitName: "Habit Name",
    description: "Description",
    dailyHabit: "Daily habit",
    selectDays: "Select Days",
    objectives: "Objectives",
    weekContract: "WEEK CONTRACT",
    rewardIfSuccessful: "Reward if successful",
    sanctionIfFail: "Sanction if you fail",
    threshold: "Threshold",
    commitContract: "Commit Contract",
    committing: "Committing...",
    reward: "Reward",
    sanction: "Sanction",
    lockedUntilNextWeek: "Locked until next week",
    swipeRightForGoals: "Swipe right for Goals & Contract →",
    swipeLeftForHabits: "← Swipe left for Habits Grid",
    
    // Pareto / To-Do
    twentyEightyRule: "20% that drives 80%",
    doThisNow: "DO THIS NOW",
    addTask: "Add Task",
    newTask: "New Task",
    whatNeedsToBeDone: "What needs to be done?",
    addDetails: "Add details...",
    priority: "Priority",
    crucial: "Crucial",
    essential: "Essential",
    average: "Average",
    low: "Low",
    otherTasks: "Other Tasks",
    noPrioritiesSet: "No priorities set",
    focusOnWhatMatters: "Focus on what truly matters",
    addFirstTask: "Add First Task",
    
    // Calendar
    new: "New",
    eventTitle: "Event title",
    eventDetails: "Event details",
    date: "Date",
    time: "Time",
    duration: "Duration",
    minutes: "minutes",
    createEvent: "Create Event",
    
    // Screen Time
    focusMode: "Focus Mode",
    deepWorkEnvironment: "Deep work environment",
    startSession: "Start Session",
    todayUsage: "Today's Usage",
    avgUsage: "7-Day Average",
    winStreak: "Win Streak",
    blockApps: "Block Apps",
    blockWebsites: "Block Websites",
    viewLeaderboard: "View Leaderboard",
    addBlockedApp: "Add Blocked App",
    addBlockedWebsite: "Add Blocked Website",
    
    // CEO Mode
    duration: "Duration",
    approvedApps: "Approved Apps",
    onceActivated: "Once activated, exit is impossible until timer expires.",
    activate: "ACTIVATE",
    activating: "ACTIVATING...",
    exit: "EXIT",
    available: "Available",
    phone: "Phone",
    messages: "Messages",
    calendar: "Calendar",
    
    // Days of week
    monday: "Mon",
    tuesday: "Tue",
    wednesday: "Wed",
    thursday: "Thu",
    friday: "Fri",
    saturday: "Sat",
    sunday: "Sun",
    
    // Settings & Legal
    settings: "Settings",
    language: "Language",
    selectLanguage: "Select Language",
    permissions: "Permissions",
    termsOfUse: "Terms of Use",
    dataDeletion: "Data Deletion",
    contact: "Contact",
    
    // Time durations
    lessThan30min: "<30min",
    oneHour: "1 hour",
    twoHours: "2 hours",
    halfDay: "Half day",
    oneDay: "1 day",
    multiDay: "Multi-day",

    // Pareto/Priority
    nothingScheduled: "Not scheduled",

    // CEO Mode
    onceActivatedCannotExit: "Once activated, exit is impossible until timer expires.",

    // Biannual Report
    monthReport: "6-Month Report",
    viewProgress: "View your progress",

    // Leaderboard
    leaderboard: "Leaderboard",
    global: "Global",
    friends: "Friends",
    addFriends: "Add Friends",

    // Week days full
    mondayFull: "Monday",
    tuesdayFull: "Tuesday",
    wednesdayFull: "Wednesday",
    thursdayFull: "Thursday",
    fridayFull: "Friday",
    saturdayFull: "Saturday",
    sundayFull: "Sunday",

    // Additional UI elements
    noHabitsToday: "No habits today",
    validating: "Validating",
    validateYesterday: "Validate Yesterday",
    yesterday: "YESTERDAY",
    validationRequired: "Validation required",
    priorities: "PRIORITIES",
    viewAll: "View All",
    blocked: "blocked",
    globalRankings: "Global rankings",
    note: "Note",
    fullBlockingNote: "Full blocking requires OS permissions. Use as tracking tool.",
    sessionComplete: "SESSION COMPLETE",
    returningHome: "Returning to home...",
    exitFocusMode: "EXIT FOCUS MODE?",
    thisWillReset: "This will RESET your",
    dayWinStreak: "-day Win Streak",
    toZero: "to ZERO",
    stayFocused: "Stay Focused",
    yesExit: "Yes, Exit",
    stayFocusedMsg: "Stay focused. You got this.",
    exitSession: "Exit Session",
    enterTheZone: "ENTER THE ZONE",
    selectDuration: "Select duration",
    customDuration: "Custom duration",
    min: "min",
    warning: "WARNING",
    earlyExitWarning: "Early exit will RESET your Win Streak to ZERO",
    currentStreak: "Current Streak",
    beginFocusMode: "BEGIN FOCUS MODE",
    starting: "Starting",
    maximumFocusDesc: "Maximum focus. Zero distractions. No escape until complete.",

    // Dashboard
    habitsForToday: "Habits for today",

    // Pareto/To-Do
    yourPriorities: "YOUR PRIORITIES",
    paretoMatrix: "Pareto Matrix",
    impactVsTime: "Impact vs Time Investment",
    doNow: "DO NOW",
    quickHighImpact: "Quick • High Impact",
    plan: "PLAN",
    takesTimeHighImpact: "Takes Time • High Impact",
    delegate: "DELEGATE",
    quickLowImpact: "Quick • Low Impact",
    eliminate: "ELIMINATE",
    takesTimeLowImpact: "Takes Time • Low Impact",
    empty: "Empty",
    swipeLeftForList: "← Swipe left for list",
    swipeRightForHistory: "Swipe right for history →",
    allTasks: "All Tasks",
    completeHistory: "Complete History",
    noTasks: "No tasks",
    addYourFirstTask: "Add your first task",
    swipeLeftToReturn: "← Swipe left to return to matrix",
    swipeRightForMatrix: "Swipe right for Matrix view →",

    // BlockingDemo
    blockingPreview: "Blocking Preview",
    normalModeBlocking: "Normal Mode Blocking",
    whenBlockedAppAccessed: "When a blocked app is accessed in normal mode, this screen appears with increased friction.",
    previewNormalMode: "Preview Normal Mode Block",
    focusModeBlocking: "Focus Mode Blocking",
    duringFocusMode: "During Focus Mode, blocked apps show a stricter screen with win streak warnings.",
    previewFocusMode: "Preview Focus Mode Block",
    productionNote: "In a production environment, these blocking screens would be triggered automatically by a browser extension or mobile app when detecting access to blocked apps/websites.",

    // ScreenTime
    restPeriod: "Rest Period",

    // Rank
    pathTo: "Path to",
    yourStats: "YOUR STATS",
    daysInApp: "Days in App",
    days: "days",
    rankLadder: "RANK LADDER",
    startingRank: "Starting rank",

    // Calendar
    newEvent: "New",
    createNewEvent: "Create New Event",
    personName: "Person's name",
    relationship: "Relationship",
    notesOptional: "Notes (Optional)",
    giftPreferences: "Gifts, preferences, etc.",
    titleEvent: "Title",
    teamMeeting: "e.g., Team meeting",
    descriptionOptional: "Description (Optional)",
    addEventDetails: "Add event details",
    durationMinutes: "Duration (minutes)",
    createBirthday: "Create Birthday",
    birthday: "Birthday",
    modeActivated: "Mode activated",
    clickToActivate: "Click to activate",

    // BiannualReport
    executiveSnapshot: "Executive Snapshot",
    last6Months: "Last 6 months",
    trendEvolution: "Trend Evolution",
    first90VsLast90: "First 90d vs. Last 90d",
    habitsConsistency: "Habits & Consistency",
    performanceByObjective: "Performance by objective",
    focusDiscipline: "Focus & Discipline",
    deepWorkPatterns: "Deep work patterns",
    paretoPriorities: "Pareto & Priorities",
    taskImpactDistribution: "Task impact distribution",
    keyInsight: "Key Insight",
    whatMattersMost: "What matters most",
    currentRank: "Current Rank",
    deepWork: "Deep Work",
    highImpact: "High-Impact",
    tasksDone: "Tasks Done",
    vsPrevious3Months: "vs. previous 3 months",
    habitExecution: "Habit Execution",
    taskVelocity: "Task Velocity",
    overallCompletionRate: "Overall Completion Rate",
    focusSessions: "Focus Sessions",
    screenTime: "Screen Time",
    dailyAverage: "Daily average",
    maximumFocusHours: "Maximum focus hours",
    highImpactWork: "High-Impact Work",
    lowPriority: "Low Priority",
    quickWins: "Quick wins",
    ofTasks: "of tasks",
    dominantInsight: "Dominant Insight",
    reportPeriod: "Report Period",
    daysTracked: "days tracked",
    },
  
  fr: {
    // Navigation & Common
    home: "Accueil",
    back: "Retour",
    loading: "Chargement",
    save: "Enregistrer",
    cancel: "Annuler",
    delete: "Supprimer",
    edit: "Modifier",
    add: "Ajouter",
    confirm: "Confirmer",
    close: "Fermer",
    
    // Home Page
    rank: "Rang",
    streak: "Série",
    habits: "Habitudes",
    today: "Aujourd'hui",
    dashboard: "Tableau de bord",
    yourDailyControlCenter: "Votre centre de contrôle quotidien",
    actionRequired: "ACTION REQUISE",
    yesterdayUnvalidated: "Hier non validé",
    todo: "Tâches",
    schedule: "Emploi du temps",
    screenTime: "Temps d'écran",
    ceoMode: "Mode PDG",
    maximumFocus: "Concentration maximale",
    
    // Menu
    sixMonthReport: "Rapport semestriel",
    yourProgressOverview: "Aperçu de vos progrès",
    activeApps: "Applications actives",
    settingsAndLegal: "Paramètres et mentions légales",
    privacyPolicy: "Politique de confidentialité",
    termsAndConditions: "Conditions générales",
    logout: "Déconnexion",
    
    // Dashboard
    controlCenter: "Centre de contrôle",
    todaysFocus: "Focus du jour",
    weekScore: "SCORE HEBDOMADAIRE",
    percent: "Pourcent",
    target: "Objectif",
    complete: "Terminé",
    youMayExit: "Vous pouvez quitter",
    remaining: "Restant",
    locked: "VERROUILLÉ",
    cannotExitEarly: "Impossible de quitter avant la fin",
    
    // Habits
    habit: "Habitude",
    goal: "Objectif",
    newHabit: "Nouvelle habitude",
    addHabit: "Ajouter une habitude",
    habitName: "Nom de l'habitude",
    description: "Description",
    dailyHabit: "Habitude quotidienne",
    selectDays: "Sélectionner les jours",
    objectives: "Objectifs",
    weekContract: "CONTRAT HEBDOMADAIRE",
    rewardIfSuccessful: "Récompense en cas de succès",
    sanctionIfFail: "Sanction en cas d'échec",
    threshold: "Seuil",
    commitContract: "Valider le contrat",
    committing: "Validation...",
    reward: "Récompense",
    sanction: "Sanction",
    lockedUntilNextWeek: "Verrouillé jusqu'à la semaine prochaine",
    swipeRightForGoals: "Glissez à droite pour Objectifs et Contrat →",
    swipeLeftForHabits: "← Glissez à gauche pour Grille d'habitudes",
    
    // Pareto / To-Do
    twentyEightyRule: "20% qui génère 80%",
    doThisNow: "À FAIRE MAINTENANT",
    addTask: "Ajouter une tâche",
    newTask: "Nouvelle tâche",
    whatNeedsToBeDone: "Qu'est-ce qui doit être fait ?",
    addDetails: "Ajouter des détails...",
    priority: "Priorité",
    crucial: "Crucial",
    essential: "Essentiel",
    average: "Moyen",
    low: "Faible",
    otherTasks: "Autres tâches",
    noPrioritiesSet: "Aucune priorité définie",
    focusOnWhatMatters: "Concentrez-vous sur l'essentiel",
    addFirstTask: "Ajouter la première tâche",
    
    // Calendar
    new: "Nouveau",
    eventTitle: "Titre de l'événement",
    eventDetails: "Détails de l'événement",
    date: "Date",
    time: "Heure",
    duration: "Durée",
    minutes: "minutes",
    createEvent: "Créer un événement",
    
    // Screen Time
    focusMode: "Mode Focus",
    deepWorkEnvironment: "Environnement de travail profond",
    startSession: "Démarrer une session",
    todayUsage: "Utilisation aujourd'hui",
    avgUsage: "Moyenne sur 7 jours",
    winStreak: "Série de victoires",
    blockApps: "Bloquer des applications",
    blockWebsites: "Bloquer des sites web",
    viewLeaderboard: "Voir le classement",
    addBlockedApp: "Ajouter une application bloquée",
    addBlockedWebsite: "Ajouter un site web bloqué",
    
    // CEO Mode
    duration: "Durée",
    approvedApps: "Applications autorisées",
    onceActivated: "Une fois activé, la sortie est impossible jusqu'à l'expiration du minuteur.",
    activate: "ACTIVER",
    activating: "ACTIVATION...",
    exit: "SORTIR",
    available: "Disponible",
    phone: "Téléphone",
    messages: "Messages",
    calendar: "Calendrier",
    
    // Days of week
    monday: "Lun",
    tuesday: "Mar",
    wednesday: "Mer",
    thursday: "Jeu",
    friday: "Ven",
    saturday: "Sam",
    sunday: "Dim",
    
    // Settings & Legal
    settings: "Paramètres",
    language: "Langue",
    selectLanguage: "Sélectionner la langue",
    permissions: "Autorisations",
    termsOfUse: "Conditions d'utilisation",
    dataDeletion: "Suppression des données",
    contact: "Contact",
    
    // Time durations
    lessThan30min: "<30min",
    oneHour: "1 heure",
    twoHours: "2 heures",
    halfDay: "Demi-journée",
    oneDay: "1 jour",
    multiDay: "Plusieurs jours",

    // Pareto/Priority
    nothingScheduled: "Non programmé",

    // CEO Mode
    onceActivatedCannotExit: "Une fois activé, la sortie est impossible jusqu'à l'expiration du minuteur.",

    // Biannual Report
    monthReport: "Rapport semestriel",
    viewProgress: "Voir votre progression",

    // Leaderboard
    leaderboard: "Classement",
    global: "Global",
    friends: "Amis",
    addFriends: "Ajouter des amis",

    // Week days full
    mondayFull: "Lundi",
    tuesdayFull: "Mardi",
    wednesdayFull: "Mercredi",
    thursdayFull: "Jeudi",
    fridayFull: "Vendredi",
    saturdayFull: "Samedi",
    sundayFull: "Dimanche",

    // Additional UI elements
    noHabitsToday: "Pas d'habitudes aujourd'hui",
    validating: "Validation",
    validateYesterday: "Valider hier",
    yesterday: "HIER",
    validationRequired: "Validation requise",
    priorities: "PRIORITÉS",
    viewAll: "Tout voir",
    blocked: "bloqué",
    globalRankings: "Classements mondiaux",
    note: "Note",
    fullBlockingNote: "Le blocage complet nécessite des autorisations du système d'exploitation. À utiliser comme outil de suivi.",
    sessionComplete: "SESSION TERMINÉE",
    returningHome: "Retour à l'accueil...",
    exitFocusMode: "QUITTER LE MODE FOCUS ?",
    thisWillReset: "Cela va RÉINITIALISER votre",
    dayWinStreak: "série de victoires de",
    toZero: "à ZÉRO",
    stayFocused: "Rester concentré",
    yesExit: "Oui, quitter",
    stayFocusedMsg: "Restez concentré. Vous pouvez le faire.",
    exitSession: "Quitter la session",
    enterTheZone: "ENTREZ DANS LA ZONE",
    selectDuration: "Sélectionner la durée",
    customDuration: "Durée personnalisée",
    min: "min",
    warning: "ATTENTION",
    earlyExitWarning: "Une sortie anticipée va RÉINITIALISER votre série de victoires à ZÉRO",
    currentStreak: "Série actuelle",
    beginFocusMode: "COMMENCER LE MODE FOCUS",
    starting: "Démarrage",
    maximumFocusDesc: "Concentration maximale. Zéro distraction. Aucune sortie avant la fin.",

    // Dashboard
    habitsForToday: "Habitudes du jour",

    // Pareto/To-Do
    yourPriorities: "VOS PRIORITÉS",
    paretoMatrix: "Matrice Pareto",
    impactVsTime: "Impact vs Investissement temps",
    doNow: "À FAIRE",
    quickHighImpact: "Rapide • Fort impact",
    plan: "PLANIFIER",
    takesTimeHighImpact: "Long • Fort impact",
    delegate: "DÉLÉGUER",
    quickLowImpact: "Rapide • Faible impact",
    eliminate: "ÉLIMINER",
    takesTimeLowImpact: "Long • Faible impact",
    empty: "Vide",
    swipeLeftForList: "← Glissez à gauche pour la liste",
    swipeRightForHistory: "Glissez à droite pour l'historique →",
    allTasks: "Toutes les tâches",
    completeHistory: "Historique complet",
    noTasks: "Aucune tâche",
    addYourFirstTask: "Ajouter votre première tâche",
    swipeLeftToReturn: "← Glissez à gauche pour retourner à la matrice",
    swipeRightForMatrix: "Glissez à droite pour la vue Matrice →",

    // BlockingDemo
    blockingPreview: "Aperçu du blocage",
    normalModeBlocking: "Blocage en Mode Normal",
    whenBlockedAppAccessed: "Quand une application bloquée est accédée en mode normal, cet écran apparaît avec une friction accrue.",
    previewNormalMode: "Aperçu Mode Normal",
    focusModeBlocking: "Blocage en Mode Focus",
    duringFocusMode: "En Mode Focus, les applications bloquées affichent un écran plus strict avec avertissement de série.",
    previewFocusMode: "Aperçu Mode Focus",
    productionNote: "En production, ces écrans de blocage seraient déclenchés automatiquement par une extension de navigateur ou une application mobile lors de la détection d'accès à des applications/sites bloqués.",

    // ScreenTime
    restPeriod: "Période de repos",

    // Rank
    pathTo: "Chemin vers",
    yourStats: "VOS STATISTIQUES",
    daysInApp: "Jours dans l'app",
    days: "jours",
    rankLadder: "ÉCHELLE DE RANGS",
    startingRank: "Rang de départ",

    // Calendar
    newEvent: "Nouveau",
    createNewEvent: "Créer un nouvel événement",
    personName: "Nom de la personne",
    relationship: "Relation",
    notesOptional: "Notes (Optionnel)",
    giftPreferences: "Cadeaux, préférences, etc.",
    titleEvent: "Titre",
    teamMeeting: "ex., Réunion d'équipe",
    descriptionOptional: "Description (Optionnel)",
    addEventDetails: "Ajouter des détails",
    durationMinutes: "Durée (minutes)",
    createBirthday: "Créer Anniversaire",
    birthday: "Anniversaire",
    modeActivated: "Mode activé",
    clickToActivate: "Cliquer pour activer",

    // BiannualReport
    executiveSnapshot: "Aperçu général",
    last6Months: "6 derniers mois",
    trendEvolution: "Évolution des tendances",
    first90VsLast90: "Premiers 90j vs. Derniers 90j",
    habitsConsistency: "Habitudes et cohérence",
    performanceByObjective: "Performance par objectif",
    focusDiscipline: "Focus et discipline",
    deepWorkPatterns: "Modèles de travail profond",
    paretoPriorities: "Pareto et priorités",
    taskImpactDistribution: "Distribution impact des tâches",
    keyInsight: "Insight clé",
    whatMattersMost: "Ce qui compte le plus",
    currentRank: "Rang actuel",
    deepWork: "Travail profond",
    highImpact: "Fort impact",
    tasksDone: "Tâches terminées",
    vsPrevious3Months: "vs. 3 mois précédents",
    habitExecution: "Exécution des habitudes",
    taskVelocity: "Vélocité des tâches",
    overallCompletionRate: "Taux de complétion global",
    focusSessions: "Sessions Focus",
    screenTime: "Temps d'écran",
    dailyAverage: "Moyenne quotidienne",
    maximumFocusHours: "Heures de focus maximum",
    highImpactWork: "Travail à fort impact",
    lowPriority: "Basse priorité",
    quickWins: "Gains rapides",
    ofTasks: "des tâches",
    dominantInsight: "Insight dominant",
    reportPeriod: "Période du rapport",
    daysTracked: "jours suivis",
    },
  
  zh: {
    // Navigation & Common
    home: "主页",
    back: "返回",
    loading: "加载中",
    save: "保存",
    cancel: "取消",
    delete: "删除",
    edit: "编辑",
    add: "添加",
    confirm: "确认",
    close: "关闭",
    
    // Home Page
    rank: "等级",
    streak: "连续",
    habits: "习惯",
    today: "今天",
    dashboard: "仪表板",
    yourDailyControlCenter: "您的每日控制中心",
    actionRequired: "需要操作",
    yesterdayUnvalidated: "昨天未验证",
    todo: "待办事项",
    schedule: "日程",
    screenTime: "屏幕时间",
    ceoMode: "CEO模式",
    maximumFocus: "最大专注",
    
    // Menu
    sixMonthReport: "六个月报告",
    yourProgressOverview: "您的进度概览",
    activeApps: "活动应用",
    settingsAndLegal: "设置和法律",
    privacyPolicy: "隐私政策",
    termsAndConditions: "条款和条件",
    logout: "登出",
    
    // Dashboard
    controlCenter: "控制中心",
    todaysFocus: "今日焦点",
    weekScore: "周分数",
    percent: "百分比",
    target: "目标",
    complete: "完成",
    youMayExit: "您可以退出",
    remaining: "剩余",
    locked: "锁定",
    cannotExitEarly: "无法提前退出",
    
    // Habits
    habit: "习惯",
    goal: "目标",
    newHabit: "新习惯",
    addHabit: "添加习惯",
    habitName: "习惯名称",
    description: "描述",
    dailyHabit: "每日习惯",
    selectDays: "选择日期",
    objectives: "目标",
    weekContract: "周合约",
    rewardIfSuccessful: "成功的奖励",
    sanctionIfFail: "失败的惩罚",
    threshold: "阈值",
    commitContract: "提交合约",
    committing: "提交中...",
    reward: "奖励",
    sanction: "惩罚",
    lockedUntilNextWeek: "锁定至下周",
    swipeRightForGoals: "向右滑动查看目标和合约 →",
    swipeLeftForHabits: "← 向左滑动查看习惯网格",
    
    // Pareto / To-Do
    twentyEightyRule: "驱动80%的20%",
    doThisNow: "现在执行",
    addTask: "添加任务",
    newTask: "新任务",
    whatNeedsToBeDone: "需要做什么？",
    addDetails: "添加详情...",
    priority: "优先级",
    crucial: "关键",
    essential: "重要",
    average: "普通",
    low: "较低",
    otherTasks: "其他任务",
    noPrioritiesSet: "未设置优先级",
    focusOnWhatMatters: "专注于重要的事情",
    addFirstTask: "添加第一个任务",
    
    // Calendar
    new: "新建",
    eventTitle: "事件标题",
    eventDetails: "事件详情",
    date: "日期",
    time: "时间",
    duration: "持续时间",
    minutes: "分钟",
    createEvent: "创建事件",
    
    // Screen Time
    focusMode: "专注模式",
    deepWorkEnvironment: "深度工作环境",
    startSession: "开始会话",
    todayUsage: "今日使用",
    avgUsage: "7天平均",
    winStreak: "连胜",
    blockApps: "阻止应用",
    blockWebsites: "阻止网站",
    viewLeaderboard: "查看排行榜",
    addBlockedApp: "添加被阻止的应用",
    addBlockedWebsite: "添加被阻止的网站",
    
    // CEO Mode
    duration: "持续时间",
    approvedApps: "批准的应用",
    onceActivated: "一旦激活，在计时器到期之前无法退出。",
    activate: "激活",
    activating: "激活中...",
    exit: "退出",
    available: "可用",
    phone: "电话",
    messages: "消息",
    calendar: "日历",
    
    // Days of week
    monday: "周一",
    tuesday: "周二",
    wednesday: "周三",
    thursday: "周四",
    friday: "周五",
    saturday: "周六",
    sunday: "周日",
    
    // Settings & Legal
    settings: "设置",
    language: "语言",
    selectLanguage: "选择语言",
    permissions: "权限",
    termsOfUse: "使用条款",
    dataDeletion: "数据删除",
    contact: "联系",
    
    // Time durations
    lessThan30min: "<30分钟",
    oneHour: "1小时",
    twoHours: "2小时",
    halfDay: "半天",
    oneDay: "1天",
    multiDay: "多天",

    // Pareto/Priority
    nothingScheduled: "未安排",

    // CEO Mode
    onceActivatedCannotExit: "一旦激活，在计时器到期之前无法退出。",

    // Biannual Report
    monthReport: "六个月报告",
    viewProgress: "查看您的进度",

    // Leaderboard
    leaderboard: "排行榜",
    global: "全球",
    friends: "朋友",
    addFriends: "添加朋友",

    // Week days full
    mondayFull: "星期一",
    tuesdayFull: "星期二",
    wednesdayFull: "星期三",
    thursdayFull: "星期四",
    fridayFull: "星期五",
    saturdayFull: "星期六",
    sundayFull: "星期日",

    // Additional UI elements
    noHabitsToday: "今天没有习惯",
    validating: "验证中",
    validateYesterday: "验证昨天",
    yesterday: "昨天",
    validationRequired: "需要验证",
    priorities: "优先事项",
    viewAll: "查看全部",
    blocked: "已屏蔽",
    globalRankings: "全球排名",
    note: "注意",
    fullBlockingNote: "完全阻止需要操作系统权限。用作跟踪工具。",
    sessionComplete: "会话完成",
    returningHome: "返回主页...",
    exitFocusMode: "退出专注模式？",
    thisWillReset: "这将重置您的",
    dayWinStreak: "天连胜",
    toZero: "到零",
    stayFocused: "保持专注",
    yesExit: "是的，退出",
    stayFocusedMsg: "保持专注。你能做到。",
    exitSession: "退出会话",
    enterTheZone: "进入专区",
    selectDuration: "选择持续时间",
    customDuration: "自定义持续时间",
    min: "分钟",
    warning: "警告",
    earlyExitWarning: "提前退出将重置您的连胜到零",
    currentStreak: "当前连胜",
    beginFocusMode: "开始专注模式",
    starting: "开始中",
    maximumFocusDesc: "最大专注。零干扰。完成前无法退出。",
    },
  
  hi: {
    // Navigation & Common
    home: "होम",
    back: "वापस",
    loading: "लोड हो रहा है",
    save: "सहेजें",
    cancel: "रद्द करें",
    delete: "हटाएं",
    edit: "संपादित करें",
    add: "जोड़ें",
    confirm: "पुष्टि करें",
    close: "बंद करें",
    
    // Home Page
    rank: "रैंक",
    streak: "स्ट्रीक",
    habits: "आदतें",
    today: "आज",
    dashboard: "डैशबोर्ड",
    yourDailyControlCenter: "आपका दैनिक नियंत्रण केंद्र",
    actionRequired: "कार्रवाई आवश्यक",
    yesterdayUnvalidated: "कल मान्य नहीं",
    todo: "कार्य सूची",
    schedule: "कार्यक्रम",
    screenTime: "स्क्रीन समय",
    ceoMode: "सीईओ मोड",
    maximumFocus: "अधिकतम फोकस",
    
    // Menu
    sixMonthReport: "6 महीने की रिपोर्ट",
    yourProgressOverview: "आपकी प्रगति का अवलोकन",
    activeApps: "सक्रिय ऐप्स",
    settingsAndLegal: "सेटिंग्स और कानूनी",
    privacyPolicy: "गोपनीयता नीति",
    termsAndConditions: "नियम और शर्तें",
    logout: "लॉगआउट",
    
    // Dashboard
    controlCenter: "नियंत्रण केंद्र",
    todaysFocus: "आज का फोकस",
    weekScore: "सप्ताह स्कोर",
    percent: "प्रतिशत",
    target: "लक्ष्य",
    complete: "पूर्ण",
    youMayExit: "आप बाहर जा सकते हैं",
    remaining: "शेष",
    locked: "लॉक",
    cannotExitEarly: "जल्दी बाहर नहीं निकल सकते",
    
    // Habits
    habit: "आदत",
    goal: "लक्ष्य",
    newHabit: "नई आदत",
    addHabit: "आदत जोड़ें",
    habitName: "आदत का नाम",
    description: "विवरण",
    dailyHabit: "दैनिक आदत",
    selectDays: "दिन चुनें",
    objectives: "उद्देश्य",
    weekContract: "साप्ताहिक अनुबंध",
    rewardIfSuccessful: "सफल होने पर पुरस्कार",
    sanctionIfFail: "विफल होने पर दंड",
    threshold: "सीमा",
    commitContract: "अनुबंध करें",
    committing: "करते हुए...",
    reward: "पुरस्कार",
    sanction: "दंड",
    lockedUntilNextWeek: "अगले सप्ताह तक लॉक",
    swipeRightForGoals: "लक्ष्य और अनुबंध के लिए दाईं ओर स्वाइप करें →",
    swipeLeftForHabits: "← आदतों की ग्रिड के लिए बाईं ओर स्वाइप करें",
    
    // Pareto / To-Do
    twentyEightyRule: "20% जो 80% चलाता है",
    doThisNow: "अभी करें",
    addTask: "कार्य जोड़ें",
    newTask: "नया कार्य",
    whatNeedsToBeDone: "क्या करने की जरूरत है?",
    addDetails: "विवरण जोड़ें...",
    priority: "प्राथमिकता",
    crucial: "महत्वपूर्ण",
    essential: "आवश्यक",
    average: "औसत",
    low: "कम",
    otherTasks: "अन्य कार्य",
    noPrioritiesSet: "कोई प्राथमिकता सेट नहीं",
    focusOnWhatMatters: "महत्वपूर्ण पर ध्यान दें",
    addFirstTask: "पहला कार्य जोड़ें",
    
    // Calendar
    new: "नया",
    eventTitle: "इवेंट शीर्षक",
    eventDetails: "इवेंट विवरण",
    date: "तारीख",
    time: "समय",
    duration: "अवधि",
    minutes: "मिनट",
    createEvent: "इवेंट बनाएं",
    
    // Screen Time
    focusMode: "फोकस मोड",
    deepWorkEnvironment: "गहन कार्य वातावरण",
    startSession: "सत्र शुरू करें",
    todayUsage: "आज का उपयोग",
    avgUsage: "7-दिन की औसत",
    winStreak: "विजय स्ट्रीक",
    blockApps: "ऐप्स ब्लॉक करें",
    blockWebsites: "वेबसाइट ब्लॉक करें",
    viewLeaderboard: "लीडरबोर्ड देखें",
    addBlockedApp: "अवरुद्ध ऐप जोड़ें",
    addBlockedWebsite: "अवरुद्ध वेबसाइट जोड़ें",
    
    // CEO Mode
    duration: "अवधि",
    approvedApps: "स्वीकृत ऐप्स",
    onceActivated: "एक बार सक्रिय होने पर, टाइमर समाप्त होने तक बाहर निकलना असंभव है।",
    activate: "सक्रिय करें",
    activating: "सक्रिय हो रहा है...",
    exit: "बाहर निकलें",
    available: "उपलब्ध",
    phone: "फोन",
    messages: "संदेश",
    calendar: "कैलेंडर",
    
    // Days of week
    monday: "सोम",
    tuesday: "मंगल",
    wednesday: "बुध",
    thursday: "गुरु",
    friday: "शुक्र",
    saturday: "शनि",
    sunday: "रवि",
    
    // Settings & Legal
    settings: "सेटिंग्स",
    language: "भाषा",
    selectLanguage: "भाषा चुनें",
    permissions: "अनुमतियाँ",
    termsOfUse: "उपयोग की शर्तें",
    dataDeletion: "डेटा विलोपन",
    contact: "संपर्क",
    
    // Time durations
    lessThan30min: "<30मिनट",
    oneHour: "1 घंटा",
    twoHours: "2 घंटे",
    halfDay: "आधा दिन",
    oneDay: "1 दिन",
    multiDay: "कई दिन",

    // Pareto/Priority
    nothingScheduled: "अनुसूचित नहीं",

    // CEO Mode
    onceActivatedCannotExit: "एक बार सक्रिय होने पर, टाइमर समाप्त होने तक बाहर निकलना असंभव है।",

    // Biannual Report
    monthReport: "6 महीने की रिपोर्ट",
    viewProgress: "अपनी प्रगति देखें",

    // Leaderboard
    leaderboard: "लीडरबोर्ड",
    global: "वैश्विक",
    friends: "मित्र",
    addFriends: "मित्र जोड़ें",

    // Week days full
    mondayFull: "सोमवार",
    tuesdayFull: "मंगलवार",
    wednesdayFull: "बुधवार",
    thursdayFull: "गुरुवार",
    fridayFull: "शुक्रवार",
    saturdayFull: "शनिवार",
    sundayFull: "रविवार",

    // Additional UI elements
    noHabitsToday: "आज कोई आदतें नहीं",
    validating: "मान्यता",
    validateYesterday: "कल मान्य करें",
    yesterday: "कल",
    validationRequired: "मान्यता आवश्यक",
    priorities: "प्राथमिकताएं",
    viewAll: "सभी देखें",
    blocked: "अवरुद्ध",
    globalRankings: "वैश्विक रैंकिंग",
    note: "नोट",
    fullBlockingNote: "पूर्ण अवरोधन के लिए OS अनुमतियों की आवश्यकता है। ट्रैकिंग टूल के रूप में उपयोग करें।",
    sessionComplete: "सत्र पूर्ण",
    returningHome: "होम पर लौट रहे हैं...",
    exitFocusMode: "फोकस मोड से बाहर निकलें?",
    thisWillReset: "यह रीसेट करेगा आपका",
    dayWinStreak: "दिन की विजय स्ट्रीक",
    toZero: "शून्य पर",
    stayFocused: "केंद्रित रहें",
    yesExit: "हां, बाहर निकलें",
    stayFocusedMsg: "केंद्रित रहें। आप यह कर सकते हैं।",
    exitSession: "सत्र से बाहर निकलें",
    enterTheZone: "जोन में प्रवेश करें",
    selectDuration: "अवधि चुनें",
    customDuration: "कस्टम अवधि",
    min: "मिनट",
    warning: "चेतावनी",
    earlyExitWarning: "जल्दी बाहर निकलने से आपकी विन स्ट्रीक शून्य पर रीसेट हो जाएगी",
    currentStreak: "वर्तमान स्ट्रीक",
    beginFocusMode: "फोकस मोड शुरू करें",
    starting: "शुरू हो रहा है",
    maximumFocusDesc: "अधिकतम फोकस। शून्य विचलन। पूर्ण होने तक कोई बाहर निकलना नहीं।",
    },
  
  es: {
    // Navigation & Common
    home: "Inicio",
    back: "Atrás",
    loading: "Cargando",
    save: "Guardar",
    cancel: "Cancelar",
    delete: "Eliminar",
    edit: "Editar",
    add: "Añadir",
    confirm: "Confirmar",
    close: "Cerrar",
    
    // Home Page
    rank: "Rango",
    streak: "Racha",
    habits: "Hábitos",
    today: "Hoy",
    dashboard: "Panel",
    yourDailyControlCenter: "Tu centro de control diario",
    actionRequired: "ACCIÓN REQUERIDA",
    yesterdayUnvalidated: "Ayer sin validar",
    todo: "Tareas",
    schedule: "Horario",
    screenTime: "Tiempo de pantalla",
    ceoMode: "Modo CEO",
    maximumFocus: "Enfoque máximo",
    
    // Menu
    sixMonthReport: "Informe de 6 meses",
    yourProgressOverview: "Resumen de tu progreso",
    activeApps: "Aplicaciones activas",
    settingsAndLegal: "Configuración y legal",
    privacyPolicy: "Política de privacidad",
    termsAndConditions: "Términos y condiciones",
    logout: "Cerrar sesión",
    
    // Dashboard
    controlCenter: "Centro de control",
    todaysFocus: "Enfoque de hoy",
    weekScore: "PUNTUACIÓN SEMANAL",
    percent: "Porcentaje",
    target: "Objetivo",
    complete: "Completo",
    youMayExit: "Puedes salir",
    remaining: "Restante",
    locked: "BLOQUEADO",
    cannotExitEarly: "No se puede salir antes",
    
    // Habits
    habit: "Hábito",
    goal: "Meta",
    newHabit: "Nuevo hábito",
    addHabit: "Añadir hábito",
    habitName: "Nombre del hábito",
    description: "Descripción",
    dailyHabit: "Hábito diario",
    selectDays: "Seleccionar días",
    objectives: "Objetivos",
    weekContract: "CONTRATO SEMANAL",
    rewardIfSuccessful: "Recompensa si tienes éxito",
    sanctionIfFail: "Sanción si fallas",
    threshold: "Umbral",
    commitContract: "Confirmar contrato",
    committing: "Confirmando...",
    reward: "Recompensa",
    sanction: "Sanción",
    lockedUntilNextWeek: "Bloqueado hasta la próxima semana",
    swipeRightForGoals: "Desliza a la derecha para Metas y Contrato →",
    swipeLeftForHabits: "← Desliza a la izquierda para Cuadrícula de hábitos",
    
    // Pareto / To-Do
    twentyEightyRule: "20% que impulsa el 80%",
    doThisNow: "HAZ ESTO AHORA",
    addTask: "Añadir tarea",
    newTask: "Nueva tarea",
    whatNeedsToBeDone: "¿Qué hay que hacer?",
    addDetails: "Añadir detalles...",
    priority: "Prioridad",
    crucial: "Crucial",
    essential: "Esencial",
    average: "Promedio",
    low: "Bajo",
    otherTasks: "Otras tareas",
    noPrioritiesSet: "No hay prioridades establecidas",
    focusOnWhatMatters: "Enfócate en lo que importa",
    addFirstTask: "Añadir primera tarea",
    
    // Calendar
    new: "Nuevo",
    eventTitle: "Título del evento",
    eventDetails: "Detalles del evento",
    date: "Fecha",
    time: "Hora",
    duration: "Duración",
    minutes: "minutos",
    createEvent: "Crear evento",
    
    // Screen Time
    focusMode: "Modo Enfoque",
    deepWorkEnvironment: "Ambiente de trabajo profundo",
    startSession: "Iniciar sesión",
    todayUsage: "Uso de hoy",
    avgUsage: "Promedio de 7 días",
    winStreak: "Racha de victorias",
    blockApps: "Bloquear aplicaciones",
    blockWebsites: "Bloquear sitios web",
    viewLeaderboard: "Ver clasificación",
    addBlockedApp: "Añadir aplicación bloqueada",
    addBlockedWebsite: "Añadir sitio web bloqueado",
    
    // CEO Mode
    duration: "Duración",
    approvedApps: "Aplicaciones aprobadas",
    onceActivated: "Una vez activado, es imposible salir hasta que expire el temporizador.",
    activate: "ACTIVAR",
    activating: "ACTIVANDO...",
    exit: "SALIR",
    available: "Disponible",
    phone: "Teléfono",
    messages: "Mensajes",
    calendar: "Calendario",
    
    // Days of week
    monday: "Lun",
    tuesday: "Mar",
    wednesday: "Mié",
    thursday: "Jue",
    friday: "Vie",
    saturday: "Sáb",
    sunday: "Dom",
    
    // Settings & Legal
    settings: "Configuración",
    language: "Idioma",
    selectLanguage: "Seleccionar idioma",
    permissions: "Permisos",
    termsOfUse: "Términos de uso",
    dataDeletion: "Eliminación de datos",
    contact: "Contacto",
    
    // Time durations
    lessThan30min: "<30min",
    oneHour: "1 hora",
    twoHours: "2 horas",
    halfDay: "Media jornada",
    oneDay: "1 día",
    multiDay: "Varios días",

    // Pareto/Priority
    nothingScheduled: "No programado",

    // CEO Mode
    onceActivatedCannotExit: "Una vez activado, es imposible salir hasta que expire el temporizador.",

    // Biannual Report
    monthReport: "Informe de 6 meses",
    viewProgress: "Ver tu progreso",

    // Leaderboard
    leaderboard: "Clasificación",
    global: "Global",
    friends: "Amigos",
    addFriends: "Añadir amigos",

    // Week days full
    mondayFull: "Lunes",
    tuesdayFull: "Martes",
    wednesdayFull: "Miércoles",
    thursdayFull: "Jueves",
    fridayFull: "Viernes",
    saturdayFull: "Sábado",
    sundayFull: "Domingo",

    // Additional UI elements
    noHabitsToday: "No hay hábitos hoy",
    validating: "Validando",
    validateYesterday: "Validar ayer",
    yesterday: "AYER",
    validationRequired: "Validación requerida",
    priorities: "PRIORIDADES",
    viewAll: "Ver todo",
    blocked: "bloqueado",
    globalRankings: "Clasificaciones globales",
    note: "Nota",
    fullBlockingNote: "El bloqueo completo requiere permisos del sistema operativo. Usar como herramienta de seguimiento.",
    sessionComplete: "SESIÓN COMPLETA",
    returningHome: "Volviendo al inicio...",
    exitFocusMode: "¿SALIR DEL MODO ENFOQUE?",
    thisWillReset: "Esto va a REINICIAR tu",
    dayWinStreak: "racha de victorias de",
    toZero: "a CERO",
    stayFocused: "Mantener el enfoque",
    yesExit: "Sí, salir",
    stayFocusedMsg: "Mantén el enfoque. Tú puedes.",
    exitSession: "Salir de la sesión",
    enterTheZone: "ENTRAR EN LA ZONA",
    selectDuration: "Seleccionar duración",
    customDuration: "Duración personalizada",
    min: "min",
    warning: "ADVERTENCIA",
    earlyExitWarning: "La salida anticipada REINICIARÁ tu racha de victorias a CERO",
    currentStreak: "Racha actual",
    beginFocusMode: "COMENZAR MODO ENFOQUE",
    starting: "Iniciando",
    maximumFocusDesc: "Enfoque máximo. Cero distracciones. Sin salida hasta completar.",
    },
  
  id: {
    // Navigation & Common
    home: "Beranda",
    back: "Kembali",
    loading: "Memuat",
    save: "Simpan",
    cancel: "Batal",
    delete: "Hapus",
    edit: "Edit",
    add: "Tambah",
    confirm: "Konfirmasi",
    close: "Tutup",
    
    // Home Page
    rank: "Peringkat",
    streak: "Streak",
    habits: "Kebiasaan",
    today: "Hari ini",
    dashboard: "Dashboard",
    yourDailyControlCenter: "Pusat kontrol harian Anda",
    actionRequired: "TINDAKAN DIPERLUKAN",
    yesterdayUnvalidated: "Kemarin belum divalidasi",
    todo: "Tugas",
    schedule: "Jadwal",
    screenTime: "Waktu Layar",
    ceoMode: "Mode CEO",
    maximumFocus: "Fokus Maksimal",
    
    // Menu
    sixMonthReport: "Laporan 6 Bulan",
    yourProgressOverview: "Ringkasan kemajuan Anda",
    activeApps: "Aplikasi Aktif",
    settingsAndLegal: "Pengaturan & Legal",
    privacyPolicy: "Kebijakan Privasi",
    termsAndConditions: "Syarat & Ketentuan",
    logout: "Keluar",
    
    // Dashboard
    controlCenter: "Pusat Kontrol",
    todaysFocus: "Fokus Hari Ini",
    weekScore: "SKOR MINGGU",
    percent: "Persen",
    target: "Target",
    complete: "Selesai",
    youMayExit: "Anda boleh keluar",
    remaining: "Tersisa",
    locked: "TERKUNCI",
    cannotExitEarly: "Tidak bisa keluar lebih awal",
    
    // Habits
    habit: "Kebiasaan",
    goal: "Tujuan",
    newHabit: "Kebiasaan Baru",
    addHabit: "Tambah Kebiasaan",
    habitName: "Nama Kebiasaan",
    description: "Deskripsi",
    dailyHabit: "Kebiasaan harian",
    selectDays: "Pilih Hari",
    objectives: "Objektif",
    weekContract: "KONTRAK MINGGUAN",
    rewardIfSuccessful: "Hadiah jika berhasil",
    sanctionIfFail: "Sanksi jika gagal",
    threshold: "Ambang batas",
    commitContract: "Komit Kontrak",
    committing: "Mengkomit...",
    reward: "Hadiah",
    sanction: "Sanksi",
    lockedUntilNextWeek: "Terkunci sampai minggu depan",
    swipeRightForGoals: "Geser ke kanan untuk Tujuan & Kontrak →",
    swipeLeftForHabits: "← Geser ke kiri untuk Grid Kebiasaan",
    
    // Pareto / To-Do
    twentyEightyRule: "20% yang menggerakkan 80%",
    doThisNow: "LAKUKAN SEKARANG",
    addTask: "Tambah Tugas",
    newTask: "Tugas Baru",
    whatNeedsToBeDone: "Apa yang perlu dilakukan?",
    addDetails: "Tambah detail...",
    priority: "Prioritas",
    crucial: "Krusial",
    essential: "Penting",
    average: "Rata-rata",
    low: "Rendah",
    otherTasks: "Tugas Lain",
    noPrioritiesSet: "Tidak ada prioritas",
    focusOnWhatMatters: "Fokus pada yang penting",
    addFirstTask: "Tambah Tugas Pertama",
    
    // Calendar
    new: "Baru",
    eventTitle: "Judul acara",
    eventDetails: "Detail acara",
    date: "Tanggal",
    time: "Waktu",
    duration: "Durasi",
    minutes: "menit",
    createEvent: "Buat Acara",
    
    // Screen Time
    focusMode: "Mode Fokus",
    deepWorkEnvironment: "Lingkungan kerja mendalam",
    startSession: "Mulai Sesi",
    todayUsage: "Penggunaan Hari Ini",
    avgUsage: "Rata-rata 7 Hari",
    winStreak: "Streak Kemenangan",
    blockApps: "Blokir Aplikasi",
    blockWebsites: "Blokir Website",
    viewLeaderboard: "Lihat Papan Peringkat",
    addBlockedApp: "Tambah Aplikasi Terblokir",
    addBlockedWebsite: "Tambah Website Terblokir",
    
    // CEO Mode
    approvedApps: "Aplikasi yang Disetujui",
    onceActivated: "Setelah diaktifkan, tidak dapat keluar sampai waktu habis.",
    activate: "AKTIFKAN",
    activating: "MENGAKTIFKAN...",
    exit: "KELUAR",
    available: "Tersedia",
    phone: "Telepon",
    messages: "Pesan",
    calendar: "Kalender",
    
    // Days of week
    monday: "Sen",
    tuesday: "Sel",
    wednesday: "Rab",
    thursday: "Kam",
    friday: "Jum",
    saturday: "Sab",
    sunday: "Min",
    
    // Settings & Legal
    settings: "Pengaturan",
    language: "Bahasa",
    selectLanguage: "Pilih Bahasa",
    permissions: "Izin",
    termsOfUse: "Syarat Penggunaan",
    dataDeletion: "Penghapusan Data",
    contact: "Kontak",
    
    // Time durations
    lessThan30min: "<30mnt",
    oneHour: "1 jam",
    twoHours: "2 jam",
    halfDay: "Setengah hari",
    oneDay: "1 hari",
    multiDay: "Beberapa hari",
    
    nothingScheduled: "Tidak terjadwal",
    onceActivatedCannotExit: "Setelah diaktifkan, tidak dapat keluar sampai waktu habis.",
    monthReport: "Laporan 6 Bulan",
    viewProgress: "Lihat kemajuan Anda",
    leaderboard: "Papan Peringkat",
    global: "Global",
    friends: "Teman",
    addFriends: "Tambah Teman",
    mondayFull: "Senin",
    tuesdayFull: "Selasa",
    wednesdayFull: "Rabu",
    thursdayFull: "Kamis",
    fridayFull: "Jumat",
    saturdayFull: "Sabtu",
    sundayFull: "Minggu",
    noHabitsToday: "Tidak ada kebiasaan hari ini",
    validating: "Memvalidasi",
    validateYesterday: "Validasi Kemarin",
    yesterday: "KEMARIN",
    validationRequired: "Validasi diperlukan",
    priorities: "PRIORITAS",
    viewAll: "Lihat Semua",
    blocked: "terblokir",
    globalRankings: "Peringkat global",
    note: "Catatan",
    fullBlockingNote: "Pemblokiran penuh memerlukan izin OS. Gunakan sebagai alat pelacakan.",
    sessionComplete: "SESI SELESAI",
    returningHome: "Kembali ke beranda...",
    exitFocusMode: "KELUAR DARI MODE FOKUS?",
    thisWillReset: "Ini akan MERESET",
    dayWinStreak: "Streak Kemenangan",
    toZero: "ke NOL",
    stayFocused: "Tetap Fokus",
    yesExit: "Ya, Keluar",
    stayFocusedMsg: "Tetap fokus. Kamu bisa!",
    exitSession: "Keluar Sesi",
    enterTheZone: "MASUKI ZONA",
    selectDuration: "Pilih durasi",
    customDuration: "Durasi kustom",
    min: "mnt",
    warning: "PERINGATAN",
    earlyExitWarning: "Keluar lebih awal akan MERESET Streak Kemenangan Anda ke NOL",
    currentStreak: "Streak Saat Ini",
    beginFocusMode: "MULAI MODE FOKUS",
    starting: "Memulai",
    maximumFocusDesc: "Fokus maksimal. Tanpa gangguan. Tidak bisa keluar sampai selesai.",
  },

  ru: {
    // Navigation & Common
    home: "Главная",
    back: "Назад",
    loading: "Загрузка",
    save: "Сохранить",
    cancel: "Отмена",
    delete: "Удалить",
    edit: "Изменить",
    add: "Добавить",
    confirm: "Подтвердить",
    close: "Закрыть",
    
    // Home Page
    rank: "Ранг",
    streak: "Серия",
    habits: "Привычки",
    today: "Сегодня",
    dashboard: "Панель",
    yourDailyControlCenter: "Ваш центр управления",
    actionRequired: "ТРЕБУЕТСЯ ДЕЙСТВИЕ",
    yesterdayUnvalidated: "Вчера не подтверждено",
    todo: "Задачи",
    schedule: "Расписание",
    screenTime: "Экранное время",
    ceoMode: "Режим CEO",
    maximumFocus: "Максимальная концентрация",
    
    // Menu
    sixMonthReport: "Отчет за 6 месяцев",
    yourProgressOverview: "Обзор вашего прогресса",
    activeApps: "Активные приложения",
    settingsAndLegal: "Настройки и юридическая информация",
    privacyPolicy: "Политика конфиденциальности",
    termsAndConditions: "Условия использования",
    logout: "Выйти",
    
    // Dashboard
    controlCenter: "Центр управления",
    todaysFocus: "Фокус дня",
    weekScore: "РЕЗУЛЬТАТ НЕДЕЛИ",
    percent: "Процент",
    target: "Цель",
    complete: "Завершено",
    youMayExit: "Вы можете выйти",
    remaining: "Осталось",
    locked: "ЗАБЛОКИРОВАНО",
    cannotExitEarly: "Нельзя выйти раньше",
    
    // Habits
    habit: "Привычка",
    goal: "Цель",
    newHabit: "Новая привычка",
    addHabit: "Добавить привычку",
    habitName: "Название привычки",
    description: "Описание",
    dailyHabit: "Ежедневная привычка",
    selectDays: "Выбрать дни",
    objectives: "Цели",
    weekContract: "НЕДЕЛЬНЫЙ КОНТРАКТ",
    rewardIfSuccessful: "Награда при успехе",
    sanctionIfFail: "Санкция при неудаче",
    threshold: "Порог",
    commitContract: "Подтвердить контракт",
    committing: "Подтверждение...",
    reward: "Награда",
    sanction: "Санкция",
    lockedUntilNextWeek: "Заблокировано до следующей недели",
    swipeRightForGoals: "Свайп вправо для Целей и Контракта →",
    swipeLeftForHabits: "← Свайп влево для Сетки привычек",
    
    // Pareto / To-Do
    twentyEightyRule: "20%, которые дают 80%",
    doThisNow: "СДЕЛАТЬ СЕЙЧАС",
    addTask: "Добавить задачу",
    newTask: "Новая задача",
    whatNeedsToBeDone: "Что нужно сделать?",
    addDetails: "Добавить детали...",
    priority: "Приоритет",
    crucial: "Критично",
    essential: "Важно",
    average: "Средне",
    low: "Низко",
    otherTasks: "Другие задачи",
    noPrioritiesSet: "Нет приоритетов",
    focusOnWhatMatters: "Сосредоточьтесь на важном",
    addFirstTask: "Добавить первую задачу",
    
    // Calendar
    new: "Новое",
    eventTitle: "Название события",
    eventDetails: "Детали события",
    date: "Дата",
    time: "Время",
    duration: "Длительность",
    minutes: "минут",
    createEvent: "Создать событие",
    
    // Screen Time
    focusMode: "Режим фокуса",
    deepWorkEnvironment: "Среда глубокой работы",
    startSession: "Начать сессию",
    todayUsage: "Использование сегодня",
    avgUsage: "Среднее за 7 дней",
    winStreak: "Серия побед",
    blockApps: "Блокировать приложения",
    blockWebsites: "Блокировать сайты",
    viewLeaderboard: "Посмотреть рейтинг",
    addBlockedApp: "Добавить заблокированное приложение",
    addBlockedWebsite: "Добавить заблокированный сайт",
    
    // CEO Mode
    approvedApps: "Одобренные приложения",
    onceActivated: "После активации невозможно выйти до истечения таймера.",
    activate: "АКТИВИРОВАТЬ",
    activating: "АКТИВАЦИЯ...",
    exit: "ВЫЙТИ",
    available: "Доступно",
    phone: "Телефон",
    messages: "Сообщения",
    calendar: "Календарь",
    
    // Days of week
    monday: "Пн",
    tuesday: "Вт",
    wednesday: "Ср",
    thursday: "Чт",
    friday: "Пт",
    saturday: "Сб",
    sunday: "Вс",
    
    // Settings & Legal
    settings: "Настройки",
    language: "Язык",
    selectLanguage: "Выбрать язык",
    permissions: "Разрешения",
    termsOfUse: "Условия использования",
    dataDeletion: "Удаление данных",
    contact: "Контакт",
    
    // Time durations
    lessThan30min: "<30мин",
    oneHour: "1 час",
    twoHours: "2 часа",
    halfDay: "Полдня",
    oneDay: "1 день",
    multiDay: "Несколько дней",
    
    nothingScheduled: "Не запланировано",
    onceActivatedCannotExit: "После активации невозможно выйти до истечения таймера.",
    monthReport: "Отчет за 6 месяцев",
    viewProgress: "Просмотр вашего прогресса",
    leaderboard: "Рейтинг",
    global: "Глобальный",
    friends: "Друзья",
    addFriends: "Добавить друзей",
    mondayFull: "Понедельник",
    tuesdayFull: "Вторник",
    wednesdayFull: "Среда",
    thursdayFull: "Четверг",
    fridayFull: "Пятница",
    saturdayFull: "Суббота",
    sundayFull: "Воскресенье",
    noHabitsToday: "Нет привычек на сегодня",
    validating: "Проверка",
    validateYesterday: "Подтвердить вчера",
    yesterday: "ВЧЕРА",
    validationRequired: "Требуется подтверждение",
    priorities: "ПРИОРИТЕТЫ",
    viewAll: "Посмотреть все",
    blocked: "заблокировано",
    globalRankings: "Глобальные рейтинги",
    note: "Примечание",
    fullBlockingNote: "Полная блокировка требует разрешений ОС. Используйте как инструмент отслеживания.",
    sessionComplete: "СЕССИЯ ЗАВЕРШЕНА",
    returningHome: "Возврат на главную...",
    exitFocusMode: "ВЫЙТИ ИЗ РЕЖИМА ФОКУСА?",
    thisWillReset: "Это СБРОСИТ вашу",
    dayWinStreak: "серию побед",
    toZero: "до НУЛЯ",
    stayFocused: "Оставайтесь сосредоточенным",
    yesExit: "Да, выйти",
    stayFocusedMsg: "Оставайтесь сосредоточенным. Вы можете это сделать.",
    exitSession: "Выйти из сессии",
    enterTheZone: "ВОЙТИ В ЗОНУ",
    selectDuration: "Выбрать длительность",
    customDuration: "Пользовательская длительность",
    min: "мин",
    warning: "ПРЕДУПРЕЖДЕНИЕ",
    earlyExitWarning: "Ранний выход СБРОСИТ вашу серию побед до НУЛЯ",
    currentStreak: "Текущая серия",
    beginFocusMode: "НАЧАТЬ РЕЖИМ ФОКУСА",
    starting: "Начало",
    maximumFocusDesc: "Максимальная концентрация. Никаких отвлечений. Выход невозможен до завершения.",
  },

  pt: {
    // Navigation & Common
    home: "Início",
    back: "Voltar",
    loading: "Carregando",
    save: "Salvar",
    cancel: "Cancelar",
    delete: "Excluir",
    edit: "Editar",
    add: "Adicionar",
    confirm: "Confirmar",
    close: "Fechar",
    
    // Home Page
    rank: "Classificação",
    streak: "Sequência",
    habits: "Hábitos",
    today: "Hoje",
    dashboard: "Painel",
    yourDailyControlCenter: "Seu centro de controle diário",
    actionRequired: "AÇÃO NECESSÁRIA",
    yesterdayUnvalidated: "Ontem não validado",
    todo: "Tarefas",
    schedule: "Agenda",
    screenTime: "Tempo de Tela",
    ceoMode: "Modo CEO",
    maximumFocus: "Foco Máximo",
    
    // Menu
    sixMonthReport: "Relatório de 6 meses",
    yourProgressOverview: "Visão geral do seu progresso",
    activeApps: "Aplicativos Ativos",
    settingsAndLegal: "Configurações e Legal",
    privacyPolicy: "Política de Privacidade",
    termsAndConditions: "Termos e Condições",
    logout: "Sair",
    
    // Dashboard
    controlCenter: "Centro de Controle",
    todaysFocus: "Foco de Hoje",
    weekScore: "PONTUAÇÃO DA SEMANA",
    percent: "Porcentagem",
    target: "Meta",
    complete: "Completo",
    youMayExit: "Você pode sair",
    remaining: "Restante",
    locked: "BLOQUEADO",
    cannotExitEarly: "Não pode sair mais cedo",
    
    // Habits
    habit: "Hábito",
    goal: "Objetivo",
    newHabit: "Novo Hábito",
    addHabit: "Adicionar Hábito",
    habitName: "Nome do Hábito",
    description: "Descrição",
    dailyHabit: "Hábito diário",
    selectDays: "Selecionar Dias",
    objectives: "Objetivos",
    weekContract: "CONTRATO SEMANAL",
    rewardIfSuccessful: "Recompensa se bem-sucedido",
    sanctionIfFail: "Sanção se falhar",
    threshold: "Limite",
    commitContract: "Comprometer Contrato",
    committing: "Comprometendo...",
    reward: "Recompensa",
    sanction: "Sanção",
    lockedUntilNextWeek: "Bloqueado até a próxima semana",
    swipeRightForGoals: "Deslize para a direita para Objetivos e Contrato →",
    swipeLeftForHabits: "← Deslize para a esquerda para Grade de Hábitos",
    
    // Pareto / To-Do
    twentyEightyRule: "20% que impulsiona 80%",
    doThisNow: "FAÇA ISSO AGORA",
    addTask: "Adicionar Tarefa",
    newTask: "Nova Tarefa",
    whatNeedsToBeDone: "O que precisa ser feito?",
    addDetails: "Adicionar detalhes...",
    priority: "Prioridade",
    crucial: "Crucial",
    essential: "Essencial",
    average: "Média",
    low: "Baixa",
    otherTasks: "Outras Tarefas",
    noPrioritiesSet: "Nenhuma prioridade definida",
    focusOnWhatMatters: "Foque no que importa",
    addFirstTask: "Adicionar Primeira Tarefa",
    
    // Calendar
    new: "Novo",
    eventTitle: "Título do evento",
    eventDetails: "Detalhes do evento",
    date: "Data",
    time: "Hora",
    duration: "Duração",
    minutes: "minutos",
    createEvent: "Criar Evento",
    
    // Screen Time
    focusMode: "Modo Foco",
    deepWorkEnvironment: "Ambiente de trabalho profundo",
    startSession: "Iniciar Sessão",
    todayUsage: "Uso de Hoje",
    avgUsage: "Média de 7 Dias",
    winStreak: "Sequência de Vitórias",
    blockApps: "Bloquear Apps",
    blockWebsites: "Bloquear Sites",
    viewLeaderboard: "Ver Classificação",
    addBlockedApp: "Adicionar App Bloqueado",
    addBlockedWebsite: "Adicionar Site Bloqueado",
    
    // CEO Mode
    approvedApps: "Aplicativos Aprovados",
    onceActivated: "Uma vez ativado, sair é impossível até o timer expirar.",
    activate: "ATIVAR",
    activating: "ATIVANDO...",
    exit: "SAIR",
    available: "Disponível",
    phone: "Telefone",
    messages: "Mensagens",
    calendar: "Calendário",
    
    // Days of week
    monday: "Seg",
    tuesday: "Ter",
    wednesday: "Qua",
    thursday: "Qui",
    friday: "Sex",
    saturday: "Sáb",
    sunday: "Dom",
    
    // Settings & Legal
    settings: "Configurações",
    language: "Idioma",
    selectLanguage: "Selecionar Idioma",
    permissions: "Permissões",
    termsOfUse: "Termos de Uso",
    dataDeletion: "Exclusão de Dados",
    contact: "Contato",
    
    // Time durations
    lessThan30min: "<30min",
    oneHour: "1 hora",
    twoHours: "2 horas",
    halfDay: "Meio dia",
    oneDay: "1 dia",
    multiDay: "Vários dias",
    
    nothingScheduled: "Não agendado",
    onceActivatedCannotExit: "Uma vez ativado, sair é impossível até o timer expirar.",
    monthReport: "Relatório de 6 meses",
    viewProgress: "Ver seu progresso",
    leaderboard: "Classificação",
    global: "Global",
    friends: "Amigos",
    addFriends: "Adicionar Amigos",
    mondayFull: "Segunda-feira",
    tuesdayFull: "Terça-feira",
    wednesdayFull: "Quarta-feira",
    thursdayFull: "Quinta-feira",
    fridayFull: "Sexta-feira",
    saturdayFull: "Sábado",
    sundayFull: "Domingo",
    noHabitsToday: "Sem hábitos hoje",
    validating: "Validando",
    validateYesterday: "Validar Ontem",
    yesterday: "ONTEM",
    validationRequired: "Validação necessária",
    priorities: "PRIORIDADES",
    viewAll: "Ver Tudo",
    blocked: "bloqueado",
    globalRankings: "Classificações globais",
    note: "Nota",
    fullBlockingNote: "Bloqueio completo requer permissões do SO. Use como ferramenta de rastreamento.",
    sessionComplete: "SESSÃO COMPLETA",
    returningHome: "Voltando para início...",
    exitFocusMode: "SAIR DO MODO FOCO?",
    thisWillReset: "Isso vai RESETAR sua",
    dayWinStreak: "Sequência de Vitórias",
    toZero: "para ZERO",
    stayFocused: "Mantenha o foco",
    yesExit: "Sim, Sair",
    stayFocusedMsg: "Mantenha o foco. Você consegue.",
    exitSession: "Sair da Sessão",
    enterTheZone: "ENTRE NA ZONA",
    selectDuration: "Selecionar duração",
    customDuration: "Duração personalizada",
    min: "min",
    warning: "AVISO",
    earlyExitWarning: "Saída antecipada vai RESETAR sua Sequência de Vitórias para ZERO",
    currentStreak: "Sequência Atual",
    beginFocusMode: "INICIAR MODO FOCO",
    starting: "Iniciando",
    maximumFocusDesc: "Foco máximo. Zero distrações. Sem saída até completar.",
  },

  ar: {
    // Navigation & Common
    home: "الرئيسية",
    back: "رجوع",
    loading: "جاري التحميل",
    save: "حفظ",
    cancel: "إلغاء",
    delete: "حذف",
    edit: "تعديل",
    add: "إضافة",
    confirm: "تأكيد",
    close: "إغلاق",
    
    // Home Page
    rank: "الرتبة",
    streak: "السلسلة",
    habits: "العادات",
    today: "اليوم",
    dashboard: "لوحة التحكم",
    yourDailyControlCenter: "مركز التحكم اليومي",
    actionRequired: "مطلوب إجراء",
    yesterdayUnvalidated: "الأمس غير مصدق",
    todo: "المهام",
    schedule: "الجدول",
    screenTime: "وقت الشاشة",
    ceoMode: "وضع الرئيس التنفيذي",
    maximumFocus: "تركيز أقصى",
    
    // Menu
    sixMonthReport: "تقرير 6 أشهر",
    yourProgressOverview: "نظرة عامة على تقدمك",
    activeApps: "التطبيقات النشطة",
    settingsAndLegal: "الإعدادات والقانونية",
    privacyPolicy: "سياسة الخصوصية",
    termsAndConditions: "الشروط والأحكام",
    logout: "تسجيل الخروج",
    
    // Dashboard
    controlCenter: "مركز التحكم",
    todaysFocus: "تركيز اليوم",
    weekScore: "نقاط الأسبوع",
    percent: "نسبة مئوية",
    target: "الهدف",
    complete: "مكتمل",
    youMayExit: "يمكنك الخروج",
    remaining: "المتبقي",
    locked: "مقفل",
    cannotExitEarly: "لا يمكن الخروج مبكراً",
    
    // Habits
    habit: "عادة",
    goal: "هدف",
    newHabit: "عادة جديدة",
    addHabit: "إضافة عادة",
    habitName: "اسم العادة",
    description: "الوصف",
    dailyHabit: "عادة يومية",
    selectDays: "اختر الأيام",
    objectives: "الأهداف",
    weekContract: "عقد الأسبوع",
    rewardIfSuccessful: "مكافأة في حالة النجاح",
    sanctionIfFail: "عقوبة في حالة الفشل",
    threshold: "العتبة",
    commitContract: "تأكيد العقد",
    committing: "جاري التأكيد...",
    reward: "مكافأة",
    sanction: "عقوبة",
    lockedUntilNextWeek: "مقفل حتى الأسبوع القادم",
    swipeRightForGoals: "اسحب لليمين للأهداف والعقد ←",
    swipeLeftForHabits: "اسحب لليسار لشبكة العادات →",
    
    // Pareto / To-Do
    twentyEightyRule: "20% التي تحرك 80%",
    doThisNow: "افعل هذا الآن",
    addTask: "إضافة مهمة",
    newTask: "مهمة جديدة",
    whatNeedsToBeDone: "ما الذي يجب القيام به؟",
    addDetails: "إضافة تفاصيل...",
    priority: "الأولوية",
    crucial: "حاسم",
    essential: "أساسي",
    average: "متوسط",
    low: "منخفض",
    otherTasks: "مهام أخرى",
    noPrioritiesSet: "لم يتم تعيين أولويات",
    focusOnWhatMatters: "ركز على ما يهم",
    addFirstTask: "إضافة المهمة الأولى",
    
    // Calendar
    new: "جديد",
    eventTitle: "عنوان الحدث",
    eventDetails: "تفاصيل الحدث",
    date: "التاريخ",
    time: "الوقت",
    duration: "المدة",
    minutes: "دقائق",
    createEvent: "إنشاء حدث",
    
    // Screen Time
    focusMode: "وضع التركيز",
    deepWorkEnvironment: "بيئة عمل عميقة",
    startSession: "بدء الجلسة",
    todayUsage: "استخدام اليوم",
    avgUsage: "متوسط 7 أيام",
    winStreak: "سلسلة الفوز",
    blockApps: "حظر التطبيقات",
    blockWebsites: "حظر المواقع",
    viewLeaderboard: "عرض لوحة المتصدرين",
    addBlockedApp: "إضافة تطبيق محظور",
    addBlockedWebsite: "إضافة موقع محظور",
    
    // CEO Mode
    duration: "المدة",
    approvedApps: "التطبيقات المعتمدة",
    onceActivated: "بمجرد التفعيل، يستحيل الخروج حتى انتهاء المؤقت.",
    activate: "تفعيل",
    activating: "جاري التفعيل...",
    exit: "خروج",
    available: "متاح",
    phone: "الهاتف",
    messages: "الرسائل",
    calendar: "التقويم",
    
    // Days of week
    monday: "الإثنين",
    tuesday: "الثلاثاء",
    wednesday: "الأربعاء",
    thursday: "الخميس",
    friday: "الجمعة",
    saturday: "السبت",
    sunday: "الأحد",
    
    // Settings & Legal
    settings: "الإعدادات",
    language: "اللغة",
    selectLanguage: "اختر اللغة",
    permissions: "الأذونات",
    termsOfUse: "شروط الاستخدام",
    dataDeletion: "حذف البيانات",
    contact: "اتصل",
    
    // Time durations
    lessThan30min: "<30 دقيقة",
    oneHour: "ساعة واحدة",
    twoHours: "ساعتان",
    halfDay: "نصف يوم",
    oneDay: "يوم واحد",
    multiDay: "عدة أيام",

    // Pareto/Priority
    nothingScheduled: "غير مجدول",

    // CEO Mode
    onceActivatedCannotExit: "بمجرد التفعيل، يستحيل الخروج حتى انتهاء المؤقت.",

    // Biannual Report
    monthReport: "تقرير 6 أشهر",
    viewProgress: "عرض تقدمك",

    // Leaderboard
    leaderboard: "لوحة المتصدرين",
    global: "عالمي",
    friends: "الأصدقاء",
    addFriends: "إضافة أصدقاء",

    // Week days full
    mondayFull: "الإثنين",
    tuesdayFull: "الثلاثاء",
    wednesdayFull: "الأربعاء",
    thursdayFull: "الخميس",
    fridayFull: "الجمعة",
    saturdayFull: "السبت",
    sundayFull: "الأحد",

    // Additional UI elements
    noHabitsToday: "لا عادات اليوم",
    validating: "التحقق",
    validateYesterday: "التحقق من الأمس",
    yesterday: "الأمس",
    validationRequired: "التحقق مطلوب",
    priorities: "الأولويات",
    viewAll: "عرض الكل",
    blocked: "محظور",
    globalRankings: "التصنيفات العالمية",
    note: "ملاحظة",
    fullBlockingNote: "الحظر الكامل يتطلب أذونات نظام التشغيل. استخدم كأداة تتبع.",
    sessionComplete: "اكتملت الجلسة",
    returningHome: "العودة إلى الصفحة الرئيسية...",
    exitFocusMode: "الخروج من وضع التركيز؟",
    thisWillReset: "هذا سيعيد تعيين",
    dayWinStreak: "سلسلة انتصاراتك",
    toZero: "إلى الصفر",
    stayFocused: "ابق مركزاً",
    yesExit: "نعم، اخرج",
    stayFocusedMsg: "ابق مركزاً. يمكنك القيام بذلك.",
    exitSession: "الخروج من الجلسة",
    enterTheZone: "ادخل المنطقة",
    selectDuration: "اختر المدة",
    customDuration: "مدة مخصصة",
    min: "دقيقة",
    warning: "تحذير",
    earlyExitWarning: "الخروج المبكر سيعيد تعيين سلسلة انتصاراتك إلى الصفر",
    currentStreak: "السلسلة الحالية",
    beginFocusMode: "ابدأ وضع التركيز",
    starting: "جاري البدء",
    maximumFocusDesc: "تركيز أقصى. لا تشتيت. لا خروج حتى الانتهاء.",
    },
};

const LanguageContext = createContext();

export function LanguageProvider({ children }) {
  const [language, setLanguage] = useState(() => {
    return localStorage.getItem('appLanguage') || 'en';
  });

  const changeLanguage = (lang) => {
    setLanguage(lang);
    localStorage.setItem('appLanguage', lang);
    
    // Update HTML dir attribute for RTL
    if (lang === 'ar') {
      document.documentElement.dir = 'rtl';
      document.documentElement.lang = 'ar';
    } else {
      document.documentElement.dir = 'ltr';
      document.documentElement.lang = lang;
    }
  };

  useEffect(() => {
    // Set initial direction
    if (language === 'ar') {
      document.documentElement.dir = 'rtl';
      document.documentElement.lang = 'ar';
    } else {
      document.documentElement.dir = 'ltr';
      document.documentElement.lang = language;
    }
  }, [language]);

  const t = (key) => {
    return translations[language]?.[key] || translations.en[key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, changeLanguage, t, isRTL: language === 'ar' }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within LanguageProvider');
  }
  return context;
}